### ISSUE TITLE
Ubiquity creates extended partitions

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mint20.1-beta#1]
LM 20 and 20.1 Cinnamon, installed with default options. Ubiquity creates an extended partition and put the / partition in it.
It is less convenient to resize a secondary partition that is inside an extended partition than to resize only one primary partition. So, why not creating an extended partition only when 4 partitions are created ? If there are only 2 or 3 partitions, primary partitions are better.

![95623699-0b7b9800-0a76-11eb-9488-f4aaa6e1bd0c](https://user-images.githubusercontent.com/3955499/102371606-a638ab80-3fbe-11eb-8294-1b4b30ca8928.png)

**Comment by clefebvre** [comment]
This is upstream from us, in Ubiquity and even in partman-auto. It's not something we plan on changing, it would need to be reported and tackled upstream directly.

**Comment by SimonIremonger** [comment]
@InfoLibre 
Can you assist finding/reporting/testing this upstream partman, ubuntu partman, as per both the issue you give, and as per related bug could carry on conversation in:-
https://github.com/linuxmint/linuxmint/issues/312
I wonder if this is sorted in ubuntu 20.10 already, for example?  -- if this can be fixed upstream, then updated partman-auto behavior could be put into Mint 20.2 installer, I would expect.
