### ISSUE TITLE
nvidia: Low-resolution after installing the driver

### ISSUE THREAD

**Issue by VaGNaroK** [linuxmint/mint20.1-beta#11]
After using the driver tool to install my gtx 650 card, when installing the driver and restarting the system, the interface is in 800x600 resolution as if the driver had not been installed (or broke the nouveau), I had to restore the system With the timeshift, I downloaded the driver from the Nvidia website NVIDIA-Linux-x86_64-455.45.01.run and installed it as requested in the manufacturer's manual and when restarting the system cinnamon is normal and works perfectly with the driver properly installed nvidia settings and even video encoder in perfect condition. The question is, is the drive manager installing something wrong and not installing the driver from the repository correctly and breaking the resolution?

Using linux mint 20.1 beta cinnamon x64

PS: needing more details let me know please.

**Comment by clefebvre** [comment]
Hi @VaGNaroK ,

Can you do the following?

- Reinstall or restore with timeshift to before you installed the drivers (either way).
- Capture the list of installed packages with `dpkg -l > list1`
- Launch the Driver Manager from the terminal with `sudo mintdrivers`
- Select the NVIDIA driver and press Apply
- Wait until it's finished installing
- Take a screenshot so we can see both the Driver Manager window and its terminal output.
- Capture the list of installed packages with `dpkg -l > list2`

Then upload list1, list2 and the terminal output here.

When you reboot, in 800x600, issue the command `inxi -Gxx` and paste its output here.

Hopefully we can spot what's wrong.

**Comment by VaGNaroK** [comment]
> Hi @VaGNaroK ,
> 
> Can you do the following?
> 
>     * Reinstall or restore with timeshift to before you installed the drivers (either way).
> 
>     * Capture the list of installed packages with `dpkg -l > list1`
> 
>     * Launch the Driver Manager from the terminal with `sudo mintdrivers`
> 
>     * Select the NVIDIA driver and press Apply
> 
>     * Wait until it's finished installing
> 
>     * Take a screenshot so we can see both the Driver Manager window and its terminal output.
> 
>     * Capture the list of installed packages with `dpkg -l > list2`
> 
> 
> Then upload list1, list2 and the terminal output here.
> 
> When you reboot, in 800x600, issue the command `inxi -Gxx` and paste its output here.
> 
> Hopefully we can spot what's wrong.

I restored the system to be without the nvidia driver installed, did as requested, created a list of packages without the nvidia driver installed:

https://gist.github.com/VaGNaroK/f057a14a45221def6b5280153645a065

**image of installing the driver along with the terminal output:**

https://postimg.cc/GH90Gr1b

**driver image installed along with the terminal output:**

https://postimg.cc/ZCKSKpqs

**package list after installing the nvidia driver:**

https://gist.github.com/VaGNaroK/fb095c621f337689a3fc71c0b6ea3e81

**resolution after restarting the system:**
https://postimg.cc/XGm25ZS5

**terminal output after installing the driver in image and text:**
https://postimg.cc/bGM0CKCc

https://gist.github.com/VaGNaroK/87f5ab1122e4ba26653b605bd87252e7

**steps I use to install the driver.**

prepare the environment by installing packages (build-essential gcc-multilib dkms), create a blacklist for nouveau at (/etc/modprobe.d/blacklist-nouveau.conf) with the options
(nouveau blacklist
options nouveau modeset = 0)
update the initramfs:
sudo update-initramfs -u
restart the pc and enter the grug in kernel recovery mode (to run the system without graphical mode), in recovery mode use the root account, look for the driver in / home, run it and do the installation:
. /NVIDIA-Linux-x86_64xxxxx.run
I finish, and restart the pc and I'm happy.

**Comment by clefebvre** [comment]
So mintdrivers installs these:

```
+ii  gcc-10-base:i386                           10.2.0-5ubuntu1~20.04               i386         GCC, the GNU Compiler Collection (base package)
+ii  libatomic1:i386                            10.2.0-5ubuntu1~20.04               i386         support library providing __atomic built-in functions
+ii  libbsd0:i386                               0.10.0-1                            i386         utility functions from BSD systems - shared library
+ii  libc6:i386                                 2.31-0ubuntu9.1                     i386         GNU C Library: Shared libraries
+ii  libcrypt1:i386                             1:4.4.10-10ubuntu4                  i386         libcrypt shared library
+ii  libdrm-amdgpu1:i386                        2.4.101-2                           i386         Userspace interface to amdgpu-specific kernel DRM services -- runtime
+ii  libdrm-intel1:i386                         2.4.101-2                           i386         Userspace interface to intel-specific kernel DRM services -- runtime
+ii  libdrm-nouveau2:i386                       2.4.101-2                           i386         Userspace interface to nouveau-specific kernel DRM services -- runtime
+ii  libdrm-radeon1:i386                        2.4.101-2                           i386         Userspace interface to radeon-specific kernel DRM services -- runtime
+ii  libdrm2:i386                               2.4.101-2                           i386         Userspace interface to kernel DRM services -- runtime
+ii  libedit2:i386                              3.1-20191231-1                      i386         BSD editline and history libraries
+ii  libelf1:i386                               0.176-1.1build1                     i386         library to read and write ELF files
+ii  libexpat1:i386                             2.2.9-1build1                       i386         XML parsing C library - runtime library
+ii  libffi7:i386                               3.3-4                               i386         Foreign Function Interface library runtime
+ii  libgcc-s1:i386                             10.2.0-5ubuntu1~20.04               i386         GCC support library
+ii  libgl1:i386                                1.3.1-1ubuntu0.20.04.1              i386         Vendor neutral GL dispatch library -- legacy GL support
+ii  libgl1-mesa-dri:i386                       20.0.8-0ubuntu1~20.04.1             i386         free implementation of the OpenGL API -- DRI modules
+ii  libglapi-mesa:i386                         20.0.8-0ubuntu1~20.04.1             i386         free implementation of the GL API -- shared library
+ii  libglvnd0:i386                             1.3.1-1ubuntu0.20.04.1              i386         Vendor neutral GL dispatch library
+ii  libglx-mesa0:i386                          20.0.8-0ubuntu1~20.04.1             i386         free implementation of the OpenGL API -- GLX vendor library
+ii  libglx0:i386                               1.3.1-1ubuntu0.20.04.1              i386         Vendor neutral GL dispatch library -- GLX support
+ii  libidn2-0:i386                             2.2.0-2                             i386         Internationalized domain names (IDNA2008/TR46) library
+ii  libllvm10:i386                             1:10.0.0-4ubuntu1                   i386         Modular compiler and toolchain technologies, runtime library
+ii  libnvidia-cfg1-455:amd64                   455.38-0ubuntu0.20.04.1             amd64        NVIDIA binary OpenGL/GLX configuration library
+ii  libnvidia-common-455                       455.38-0ubuntu0.20.04.1             all          Shared files used by the NVIDIA libraries
+ii  libnvidia-compute-455:amd64                455.38-0ubuntu0.20.04.1             amd64        NVIDIA libcompute package
+ii  libnvidia-compute-455:i386                 455.38-0ubuntu0.20.04.1             i386         NVIDIA libcompute package
+ii  libnvidia-decode-455:amd64                 455.38-0ubuntu0.20.04.1             amd64        NVIDIA Video Decoding runtime libraries
+ii  libnvidia-decode-455:i386                  455.38-0ubuntu0.20.04.1             i386         NVIDIA Video Decoding runtime libraries
+ii  libnvidia-encode-455:amd64                 455.38-0ubuntu0.20.04.1             amd64        NVENC Video Encoding runtime library
+ii  libnvidia-encode-455:i386                  455.38-0ubuntu0.20.04.1             i386         NVENC Video Encoding runtime library
+ii  libnvidia-extra-455:amd64                  455.38-0ubuntu0.20.04.1             amd64        Extra libraries for the NVIDIA driver
+ii  libnvidia-fbc1-455:amd64                   455.38-0ubuntu0.20.04.1             amd64        NVIDIA OpenGL-based Framebuffer Capture runtime library
+ii  libnvidia-fbc1-455:i386                    455.38-0ubuntu0.20.04.1             i386         NVIDIA OpenGL-based Framebuffer Capture runtime library
+ii  libnvidia-gl-455:amd64                     455.38-0ubuntu0.20.04.1             amd64        NVIDIA OpenGL/GLX/EGL/GLES GLVND libraries and Vulkan ICD
+ii  libnvidia-gl-455:i386                      455.38-0ubuntu0.20.04.1             i386         NVIDIA OpenGL/GLX/EGL/GLES GLVND libraries and Vulkan ICD
+ii  libnvidia-ifr1-455:amd64                   455.38-0ubuntu0.20.04.1             amd64        NVIDIA OpenGL-based Inband Frame Readback runtime library
+ii  libnvidia-ifr1-455:i386                    455.38-0ubuntu0.20.04.1             i386         NVIDIA OpenGL-based Inband Frame Readback runtime library
+ii  libpciaccess0:i386                         0.16-0ubuntu1                       i386         Generic PCI access library for X
+ii  libsensors5:i386                           1:3.6.0-2ubuntu1                    i386         library to read temperature/voltage/fan sensors
+ii  libstdc++6:i386                            10.2.0-5ubuntu1~20.04               i386         GNU Standard C++ Library v3
+ii  libtinfo6:i386                             6.2-0ubuntu2                        i386         shared low-level terminfo library for terminal handling
+ii  libunistring2:i386                         0.9.10-2                            i386         Unicode string library for C
+ii  libvulkan1:i386                            1.2.131.2-1                         i386         Vulkan loader library
+ii  libwayland-client0:i386                    1.18.0-1                            i386         wayland compositor infrastructure - client library
+ii  libx11-6:i386                              2:1.6.9-2ubuntu1.1                  i386         X11 client-side library
+ii  libx11-xcb1:i386                           2:1.6.9-2ubuntu1.1                  i386         Xlib/XCB interface library
+ii  libxau6:i386                               1:1.0.9-0ubuntu1                    i386         X11 authorisation library
+ii  libxcb-dri2-0:i386                         1.14-2                              i386         X C Binding, dri2 extension
+ii  libxcb-dri3-0:i386                         1.14-2                              i386         X C Binding, dri3 extension
+ii  libxcb-glx0:i386                           1.14-2                              i386         X C Binding, glx extension
+ii  libxcb-present0:i386                       1.14-2                              i386         X C Binding, present extension
+ii  libxcb-randr0:i386                         1.14-2                              i386         X C Binding, randr extension
+ii  libxcb-sync1:i386                          1.14-2                              i386         X C Binding, sync extension
+ii  libxcb1:i386                               1.14-2                              i386         X C Binding
+ii  libxdamage1:i386                           1:1.1.5-2                           i386         X11 damaged region extension library
+ii  libxdmcp6:i386                             1:1.1.3-0ubuntu1                    i386         X11 Display Manager Control Protocol library
+ii  libxext6:i386                              2:1.3.4-0ubuntu1                    i386         X11 miscellaneous extension library
+ii  libxfixes3:i386                            1:5.0.3-2                           i386         X11 miscellaneous 'fixes' extension library
+ii  libxnvctrl0:amd64                          440.82-0ubuntu0.20.04.1             amd64        NV-CONTROL X extension (runtime library)
+ii  libxshmfence1:i386                         1.3-1                               i386         X shared memory fences - shared library
+ii  libxxf86vm1:i386                           1:1.1.4-1build1                     i386         X11 XFree86 video mode extension library
+ii  libzstd1:i386                              1.4.4+dfsg-3                        i386         fast lossless compression algorithm
+ii  mesa-vulkan-drivers:i386                   20.0.8-0ubuntu1~20.04.1             i386         Mesa Vulkan graphics drivers
+ii  nvidia-compute-utils-455                   455.38-0ubuntu0.20.04.1             amd64        NVIDIA compute utilities
+ii  nvidia-dkms-455                            455.38-0ubuntu0.20.04.1             amd64        NVIDIA DKMS package
+ii  nvidia-driver-455                          455.38-0ubuntu0.20.04.1             amd64        NVIDIA driver metapackage
+ii  nvidia-kernel-common-455                   455.38-0ubuntu0.20.04.1             amd64        Shared files used with the kernel module
+ii  nvidia-kernel-source-455                   455.38-0ubuntu0.20.04.1             amd64        NVIDIA kernel source package
+ii  nvidia-prime                               0.8.14                              all          Tools to enable NVIDIA's Prime
+ii  nvidia-settings                            440.82-0ubuntu0.20.04.1             amd64        Tool for configuring the NVIDIA graphics driver
+ii  nvidia-utils-455                           455.38-0ubuntu0.20.04.1             amd64        NVIDIA driver support binaries
+ii  screen-resolution-extra                    0.18build1                          all          Extension for the nvidia-settings control panel
+ii  xserver-xorg-video-nvidia-455              455.38-0ubuntu0.20.04.1             amd64        NVIDIA binary Xorg driver
+ii  zlib1g:i386                                1:1.2.11.dfsg-2ubuntu1.2            i386         compression library - runtime

```

**Comment by clefebvre** [comment]
I can't see anything wrong in this package list. It looks like the driver manager successfully installed the right packages... 

Can you go back to after the installation (of the drivers with the driver manager) and see if the DKMS status is correct? Running the following commands should tell us your kernel (should be 5.4.0-58) and if the NVIDIA module was properly built against that kernel.

```
uname -a
dkms status
```

**Comment by VaGNaroK** [comment]
clean restored system without NVIDIA driver:

https://postimg.cc/RWmMmH5h

With the driver installed without restarting the pc:

https://postimg.cc/pmkttcJc

after restarting the system with low resolution:

https://postimg.cc/Fk02CTKZ

Already installing using the manufacturer's driver and with the method described in the second comment after restarting everything works fine as in the photo below:

https://postimg.cc/vDWfMCcv

I really have no idea what happens and I'm using the same standard kernel as the distro.

**Comment by VaGNaroK** [comment]
if you can't find the problem you can mark it as solved since I install it manually, but, strange, it seems that it does not disable the nouveau driver after installing with the mint drivers or does not blacklist the drive or update the update- initramfs -u or something. Maybe it's just me since nobody else reported it.

but the only changes I saw installing the driver from the repository with mint drivers were some strings in the following photos:
instaled driver repository:
https://postlmg.cc/bGM0CKCc
in the driver function: fbdev,modesetting,nouveau

Instaled driver nvidia oficial site:
https://postlmg.cc/vDWfMCcv
in the driver function: modesetting,nvidia

if this can be related, I have no idea.

**Comment by clefebvre** [comment]
Sorry @VaGNaroK I'm at loss here... there's obviously something wrong but looking at the list of packages and all, everything seems to install fine.

One last thing you could try is this:

- Fresh install (or snapshot back to fresh install)
- Install ubuntu nvidia driver using the command line: `apt install nvidia-driver-455`
- Reboot

See if you see any errors during the installation of the driver, and if you get full resolution post-reboot.

If you get the same issue as with mintdrivers we can rule out a bug in mintdrivers and focus on an upstream bug in the ubuntu driver.

**Comment by rogvuc** [comment]
I had similar issue with mint 20.0, my nvidia driver would not load on start up and i would be stuck in  640x480 until i manually restart x. I fixed the problem by adding
  
```
Section "Files"
    ModulePath      "/usr/lib/x86_64-linux-gnu/nvidia/xorg"
    ModulePath      "/usr/lib/xorg/modules"
EndSection
```

to my conf.xorg as described in [this](https://forums.linuxmint.com/viewtopic.php?f=208&t=327160) post on  linux mint forums.
I hope this offers some clue to what is going on here because this issue sounds relay similar at least to me. Sorry if this is not the right place/way to offer my opinion on this problem, hope this helps

**Comment by clefebvre** [comment]
I can't reproduce the issue. Tested with mintdrivers on a GTX 1660ti. I'm gonna have to assume it's upstream from us and not related to mintdrivers itself. Please reopen a new issue with mintdrivers if you find out this assumption was wrong (i.e. if installing the drivers directly with APT works, but installing them with mintdrivers doesn't).
