### ISSUE TITLE
Nemo - Deleted folders are kept in favorites

### ISSUE THREAD

**Issue by MenthaSuaveolens** [linuxmint/mint20.1-beta#13]
![DeletedFolders](https://user-images.githubusercontent.com/47174957/102465122-8d2b0b80-404d-11eb-9a32-6bfc374ec8f0.png)
1. Add a folder to favorites
2. Delete folder (or delete parent-folder)
3. Folder is still shown in favorites
4. Remove from favorites => nemo crashes?
5. Folder is still shown in favorites

**Comment by clefebvre** [comment]
I can't reproduce this.. it works fine for me here..

Can you pastebin the stack trace from mintreport?

**Comment by mtwebster** [comment]
I can reproduce.

**Comment by MenthaSuaveolens** [comment]
Stacktrace on https://termbin.com/q6ua or in appendix
[StackTrace.txt](https://github.com/linuxmint/mint20.1-beta/files/5710610/StackTrace.txt)

**Comment by MenthaSuaveolens** [comment]
The only way to remove the removed folders from favorites is to create the folders again. As soon as the folder is created it is tagged by the favorites-star. Then one can remove the folder from the favorites.
![NemoFavoritesCrash](https://user-images.githubusercontent.com/47174957/102512291-2710a980-408a-11eb-93ee-9b35909f90c1.png)

**Comment by mtwebster** [comment]
ref:
https://github.com/linuxmint/nemo/commit/588785d26ca6aa3966f91b373fc31d878d24cb78
https://github.com/linuxmint/nemo/commit/551f4ca62332336d056981b77ebc4b95a05633d2
https://github.com/linuxmint/xapp/commit/12808ba6dd15d49deab0219bd14229a573f050d3
