### ISSUE TITLE
Printing - Not perfect

### ISSUE THREAD

**Issue by proulxf012** [linuxmint/mint20.1-beta#14]
1) Unable to print 2 sided on the same sheet of paper.
2) Printer is re-added by "the system" as soon as I try to delete it to try to add it manually. It happens within 1 second.
3) The printer has 2 listing when I try to print. The listing with "-" in the name does nothing. Simply, nothing happens.
Note: Printer is a Canon TR7520. The printer is connected with a USB cable to a Windows 10 desktop. My Linux laptop is connected to the printer by wi-fi. The printer worked perfectly with LM 19.x.
Here are the requested commands post:
[lsusb.txt](https://github.com/linuxmint/mint20.1-beta/files/5713041/lsusb.txt)
[dpkg -l.txt](https://github.com/linuxmint/mint20.1-beta/files/5713045/dpkg.-l.txt)
[lpstat -t.txt](https://github.com/linuxmint/mint20.1-beta/files/5713046/lpstat.-t.txt)
[scanimage -L.txt](https://github.com/linuxmint/mint20.1-beta/files/5713048/scanimage.-L.txt)
![Printing](https://user-images.githubusercontent.com/42395236/102562595-6993af80-40a5-11eb-97b4-de2cd613a003.png)

Regards

**Comment by SimonIremonger** [comment]
Wondering if this is result of changes as per:-
https://github.com/linuxmint/linuxmint/issues/327
I do think "automatically adding all network announced printers" may not be helpful for everybody....

**Comment by clefebvre** [comment]
no, the outcome of https://github.com/linuxmint/linuxmint/issues/327 was to remove IPP.

**Comment by clefebvre** [comment]
```
$ lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 04f2:b649 Chicony Electronics Co., Ltd Chicony USB2.0 Camera
Bus 001 Device 003: ID 8087:0aaa Intel Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
No ipp-usb not ippusbxd in dpkg -l output..

```
$ lpstat -t
scheduler is running
no system default destination
matériel pour Canon_TR7500_series : implicitclass://Canon_TR7500_series/
Canon_TR7500_series accepte des requêtes depuis jeu 17 déc 2020 13:37:36
printer Canon_TR7500_series is idle.  enabled since jeu 17 déc 2020 13:37:36
```

```
$ scanimage -L
device `escl:https://10.0.0.151:443' is a ESCL Canon TR7500 series SSL flatbed scanner
device `escl:http://10.0.0.151:80' is a ESCL Canon TR7500 series flatbed scanner
```

**Comment by clefebvre** [comment]
Ok, the reason the absence of ipp-usb and ipusbxd have no effect here is because it's not connected via USB, but shared via network. If you want to stop it from re-appearing all the time, try to remove `cups-browsed`.

Then after that, reboot, and see if you can add it manually and if that works better.

**Comment by SimonIremonger** [comment]
@proulxf012, beyond the above (connect to network manually), I note:-

I note that the TR7500 is not listed here, where I would normally expect driver choices and so-on:-
https://openprinting.org/printers/manufacturer/Canon
So, you could let us know what print driver is being selected, and if you had to add manually -- that could be a known bug in drivers, ubuntu 20.04 might be able to refer to, and so-on. 

I note another avenue that could be *tested* is temporarily connect the printer via USB to the linuxmint and see if that behaves the same for duplex-printing etc.
If there are also *scanning* issues they are likely down to the known-problematic "escl" driver / sane-backends in 20.04 which could arguably be updated/backported usefully.

**Comment by proulxf012** [comment]
Hi. I removed "cups-browsed" and that worked, I can now remove/add the printer at will. Adding the printer worked exactly as in LM 19.x. But the problem with the 2 sided printing remains. I think that this is an issue with cups and the drivers that are included in it.
I tried adding the printer with Canon's own drivers but the install script works with the "cabled" install but stubbornly refuses to "find" the printer on the network. LM 20 & 20.1 do not have any problem finding the printer to add it. That may be a problem with Canon's install script. If it is I am stuck printing 2 sided manually.
Thank you all for trying.
Regards

**Comment by clefebvre** [comment]
Well hold on.. there are two other things you can try. What you're using over the network is IPP.

- First you can try to install ipp-usb from the repositories (same thing, remove the printer and reboot) and see if that helps... it don't think it will. I think ipp-usb is limited to USB connections, but hey.. you never know. I didn't look at its source code yet so I only have a vague idea of its design still.
- Second, you can try and upgrade cups to 2.3.3... you'll need to get your hands dirty here. Either find someone who packaged 2.3.3 for Focal (Ubuntu 20.04) or compile/package it yourself. This PPA here has it done for Bionic, so with minimum efforts it should compile in Focal: https://launchpad.net/~thierry-f/+archive/ubuntu/printers-and-scanners/+packages.

**Comment by proulxf012** [comment]
I just thought to try that: cabled installation with Canon's install script (and drivers) works as advertised with 2 sided printing working perfectly. So Canon's own drivers work but the install script refuses to install the drivers to print wireless because it can not find the printer during installation. But cups sees the printer without problem, it just can't get to the proper drivers. "sigh"
Regards
To Clem: OK i'll try it. "shivers"

**Comment by proulxf012** [comment]
As expected installing ipp-usb did not help. 
I was able to add the PPA for the cups build but apt (and apt-get) will not install anything above cups 2.3.1. What am I missing?
Regards

**Comment by proulxf012** [comment]
I just saw, while trying to convince synaptic to install cups 2.3.3, that the canon drivers (cnijfilter2)  are installed and present on my laptop. cups just won't used them. Is there a way to make cups use the drivers present on the laptop?
Regards

**Comment by clefebvre** [comment]
OK, sorry I realize this isn't necessarily easy to do if you're not a developer. I compiled cups 2.3.3 and the newer cups filter for you. The packages in the archive below are compiled for Mint 20.1:

[cups-2.3.3-mint20.1.zip](https://github.com/linuxmint/mint20.1-beta/files/5718011/cups-2.3.3-mint20.1.zip)

Before you install them, remove ipp-usb and make a timeshift snapshot (so you can go back if you want to later on). You can see your list of installed cups with:

```
dpkg -l | grep 2.3.1-9ubuntu1.1
dpkg -l | grep 1.27.4-1
```

You don't need to install .debs that aren't in that list, just upgrade the ones you have using the debs.

`sudo dpkg -i file1.deb file2.deb file3.deb etc...`

Reboot then and make sure your cups packages are all 2.3.3 and  1.27.5.

**Comment by proulxf012** [comment]
Hi Clem.
Thank you for your time. This is a lot of work for an almost 62 y.o. dabbler in something he hardly understands. Cups packages were easy to update. Cups-filters (1.27.5 series) ran into what I saw called dependence hell. Wanted -dev of cups. I think I will stick with manual 2 sided printing, will be better for my heart that I go up the stairs from the basement. Not a lot of bother but I found it interesting to try to solve as it might help others. Anyway, thank you again for your time.
Regards

**Comment by clefebvre** [comment]
No problem. You probably tried to install too many of the .debs (the -dev ones in particular will have many dependencies, they're packages for development, you shouldn't install these).

I'll close this issue. Thank you for your time.

**Comment by clefebvre** [comment]
Hi @proulxf012,

Just in case it helps, I just realized I had your package list already, so I know exactly which packages you have installed. You might want to restore your timeshift snapshot first in case you installed -dev packages.. but after that, the archive below only contains upgrades for the packages you already have, so in this one, you can install all the packages without exception.

[debs.zip](https://github.com/linuxmint/mint20.1-beta/files/5718696/debs.zip)

Unzip it, go in the directory and run `sudo dpkg -i *.deb`
