### ISSUE TITLE
Translations: Celluloid and Gnote language packs

### ISSUE THREAD

**Issue by mahtiankka** [linuxmint/mint20.1-beta#18]
Celluloid and Gnote language packs are missing. At least in Finnish. I've done both completed a few months ago. Maybe the sync didn't work? Tested Cinnamon.
![celluloid_gnote](https://user-images.githubusercontent.com/48694735/102675486-3edb5100-41a2-11eb-85d1-f70397976c56.png)

**Comment by VaGNaroK** [comment]
this is a problem with the translation team not having done all the translations on the launchpad or it may be that the translations there on the launchpad are not being added to the final source files, this has happened before, even with everything translated on the launchpad, but in the end compiled with the translation done.

**Comment by clefebvre** [comment]
in French I get it mostly translated.

![image](https://user-images.githubusercontent.com/1138515/103426674-12b4cc80-4bb3-11eb-8b71-d3bef57de25b.png)

I'll check the po and commits.

**Comment by hugok79** [comment]
Celluloid is translated in https://translate.zanata.org/iteration/view/celluloid/master?dswid=6107 
The last sync of the translations “.po files” was on 10 oct 2020

**Comment by hugok79** [comment]
The Gnote translations come from the Gnome Translations...

**Comment by clefebvre** [comment]
We're shipping Celluloid 0.20 so the translations sync for us is September... still, looking at the fi.po, these translations should be there: https://github.com/linuxmint/celluloid/blob/mint20.1/po/fi.po#L760.

**Comment by clefebvre** [comment]
For gnote it's upstream from us, we ship the focal version directly.

**Comment by clefebvre** [comment]
@mahtiankka launch mintlocale and make sure all the language packs are installed.

![image](https://user-images.githubusercontent.com/1138515/103437666-f8660780-4c21-11eb-85a2-6d8d77107044.png)

Make sure it's all green for Finnish ^^

**Comment by clefebvre** [comment]
OK, I can reproduce this.

![image](https://user-images.githubusercontent.com/1138515/103437712-ba1d1800-4c22-11eb-9309-246809483a20.png)

**Comment by hugok79** [comment]
In portuguese (pt) Celluloid translations are fine... no problems here.

**Comment by clefebvre** [comment]
Ok, here's a first element of causality...

```
clem@airtop ~ $ apt content celluloid | grep celluloid.mo
/usr/share/locale/bg/LC_MESSAGES/celluloid.mo
/usr/share/locale/ca/LC_MESSAGES/celluloid.mo
/usr/share/locale/cs/LC_MESSAGES/celluloid.mo
/usr/share/locale/da/LC_MESSAGES/celluloid.mo
/usr/share/locale/de/LC_MESSAGES/celluloid.mo
/usr/share/locale/eo/LC_MESSAGES/celluloid.mo
/usr/share/locale/es/LC_MESSAGES/celluloid.mo
/usr/share/locale/fa/LC_MESSAGES/celluloid.mo
/usr/share/locale/fr/LC_MESSAGES/celluloid.mo
/usr/share/locale/hr/LC_MESSAGES/celluloid.mo
/usr/share/locale/hu/LC_MESSAGES/celluloid.mo
/usr/share/locale/it/LC_MESSAGES/celluloid.mo
/usr/share/locale/ja/LC_MESSAGES/celluloid.mo
/usr/share/locale/nl/LC_MESSAGES/celluloid.mo
/usr/share/locale/pl/LC_MESSAGES/celluloid.mo
/usr/share/locale/pt_BR/LC_MESSAGES/celluloid.mo
/usr/share/locale/pt_PT/LC_MESSAGES/celluloid.mo
/usr/share/locale/ro/LC_MESSAGES/celluloid.mo
/usr/share/locale/ru/LC_MESSAGES/celluloid.mo
/usr/share/locale/sl/LC_MESSAGES/celluloid.mo
/usr/share/locale/sr@latin/LC_MESSAGES/celluloid.mo
/usr/share/locale/sr/LC_MESSAGES/celluloid.mo
/usr/share/locale/sv/LC_MESSAGES/celluloid.mo
/usr/share/locale/tr/LC_MESSAGES/celluloid.mo
/usr/share/locale/uk/LC_MESSAGES/celluloid.mo
/usr/share/locale/zh_CN/LC_MESSAGES/celluloid.mo
/usr/share/locale/zh_TW/LC_MESSAGES/celluloid.mo
```

**Comment by clefebvre** [comment]
OK, I can see what's wrong fi is missing from po/LINGUAS.

**Comment by clefebvre** [comment]
Reported upstream https://github.com/celluloid-player/celluloid/pull/616
We'll patch this locally in the meantime and send an update.

**Comment by clefebvre** [comment]
![image](https://user-images.githubusercontent.com/1138515/103438320-0a4ba880-4c2a-11eb-9164-0567ee28df5b.png)
