### ISSUE TITLE
Wrong french keyboard is selected by default in Ubiquity

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mint20.1-beta#2]
When we install Linux Mint 20 or 20.1 Cinnamon in French, "Francais (azerty)" or "Francais" (no variant) should be the default selected keyboard, instead of "Français (variante obsolète)".

https://bugs.launchpad.net/ubuntu/+source/ubiquity/+bug/1807344
#50
linuxmint/mint20-beta#6
https://github.com/linuxmint/linuxmint/issues/310

**Comment by clefebvre** [comment]
Yes, that was the case in 20 already. It's an upstream issue. We had plans to tackle it by rewriting the keyboard selection in Ubiquity but it didn't happen in this release cycle. It's still in the roadmap for 20.2.
