### ISSUE TITLE
Cinnamon desktop context menu cropped after display scale change

### ISSUE THREAD

**Issue by schluetermichael** [linuxmint/mint20.1-beta#21]
I did a fresh installed of Mint 20.1 Cinnamon Beta, installed all updates as of Dec 19th and switched to the nvidia-455 driver (GTX 1060).
After a reboot I changed the display scale to 150% (see screen shot).

![Change display scale](https://user-images.githubusercontent.com/13156489/102689082-c903d380-41fb-11eb-886d-00fa9fdb1ef3.png)

Afterwards, the context menu of the Cinnamon desktop was cropped since the menu items are scaled to 150% but the menu window size is still at 100%. Another reboot fixes the problem. 
![Cropped context menu](https://user-images.githubusercontent.com/13156489/102689362-b8545d00-41fd-11eb-8467-e90c46944e6a.png)

**Comment by clefebvre** [comment]
Thanks @schluetermichael. I think it's OK for 20.1. It's a papercut obviously. In 20.2 we'll change this UI a little bit and recommend a logout when fractional/hidpi scales are changed.
