### ISSUE TITLE
Mint-X Icons: System-Settings, Online Accounts -- Developer Intent

### ISSUE THREAD

**Issue by Acheron17** [linuxmint/mint20.1-beta#22]
In Mint 20 for the Mint-X Icons, there was no dedicated icon for cs-online-accounts so it picked up cs-online-accounts.svg in /usr/share/icons/hicolor/scalable/categories which was a close match for Mint-Y.

In Mint 20.1 there is now a set of the default GNOME icons in /usr/share/icons/hicolor/??x??/apps so it picks one of those up before /usr/share/icons/hicolor/scalable/categories.

Is this the developer intent?

![icons](https://user-images.githubusercontent.com/45599505/102691498-03a94400-41db-11eb-89d5-9fba6a7b6db0.png)

**Comment by Acheron17** [comment]
Before the beta is wrapped up, could someone please take a look at this.  I'm sure its a simple fix.

**Comment by clefebvre** [comment]
Yes, it's planned.

**Comment by Acheron17** [comment]
Thank you kindly.

**Comment by clefebvre** [comment]
Fixed in mint-x-icons 1.5.9.
