### ISSUE TITLE
Mint 20.1 Random Rebooting

### ISSUE THREAD

**Issue by obxwindsurfer** [linuxmint/mint20.1-beta#24]
Bug reported in Mint 20.0 (https://github.com/linuxmint/linuxmint/issues/306) still occurring in Mint 20.1.

Started with a fresh default installation onto full hard drive. Installed recommended Nvidia driver. Installed software updates.
Next, opened several default installed applications. Within a few minutes the system crashes and reboots. This is very repeatable and nothing has changed in going from Mint 20.0 to Mint 20.1.

As previously reported, this problem does not occur with Mint 19.3. It also does not occur with MX Linux 19.2 nor with the most recent MX Linux 19.3 release.

System configuration:

```
System:
  Kernel: 5.4.0-58-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 
  Desktop: Cinnamon 4.8.3 wm: muffin dm: LightDM 
  Distro: Linux Mint 20.1 Ulyssa base: Ubuntu 20.04 focal 
Machine:
  Type: Desktop Mobo: Gigabyte model: X58A-UD3R serial: <filter> BIOS: Award 
  v: F6 date: 08/24/2010 
CPU:
  Topology: Quad Core model: Intel Core i7 930 bits: 64 type: MT MCP 
  arch: Nehalem rev: 5 L2 cache: 8192 KiB 
  flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 45339 
  Speed: 1619 MHz min/max: 1596/2794 MHz Core speeds (MHz): 1: 1619 2: 1619 
  3: 1619 4: 1619 5: 1619 6: 1619 7: 1619 8: 1619 
Graphics:
  Device-1: NVIDIA GK208B [GeForce GT 710] vendor: Gigabyte driver: nvidia 
  v: 455.38 bus ID: 03:00.0 chip ID: 10de:128b 
  Display: x11 server: X.Org 1.20.8 driver: nvidia 
  unloaded: fbdev,modesetting,nouveau,vesa resolution: 1920x1080~60Hz 
  OpenGL: renderer: GeForce GT 710/PCIe/SSE2 v: 4.6.0 NVIDIA 455.38 
  direct render: Yes 
Audio:
  Device-1: Intel 82801JI HD Audio 
  vendor: Gigabyte GA-EP45-DS5/GA-EG45M-DS2H driver: snd_hda_intel v: kernel 
  bus ID: 00:1b.0 chip ID: 8086:3a3e 
  Device-2: NVIDIA GK208 HDMI/DP Audio vendor: Gigabyte 
  driver: snd_hda_intel v: kernel bus ID: 03:00.1 chip ID: 10de:0e0f 
  Device-3: Hauppauge WinTV HVR-950 type: USB driver: au0828,snd-usb-audio 
  bus ID: 9-1:2 chip ID: 2040:7200 
  Sound Server: ALSA v: k5.4.0-58-generic 
Network:
  Device-1: Qualcomm Atheros AR93xx Wireless Network Adapter driver: ath9k 
  v: kernel port: db00 bus ID: 08:00.0 chip ID: 168c:0030 
  IF: wlp8s0 state: down mac: <filter> 
  Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet 
  vendor: Gigabyte driver: r8169 v: kernel port: ae00 bus ID: 0a:00.0 
  chip ID: 10ec:8168 
  IF: enp10s0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
  Device-3: D-Link System DGE-528T Gigabit Ethernet Adapter driver: r8169 
  v: kernel port: ce00 bus ID: 0b:00.0 chip ID: 1186:4300 
  IF: enp11s0 state: down mac: <filter> 
Drives:
  Local Storage: total: 931.51 GiB used: 9.05 GiB (1.0%) 
  ID-1: /dev/sda vendor: Seagate model: ST1000DM003-9YN162 size: 931.51 GiB 
  speed: 1.5 Gb/s serial: <filter> 
Partition:
  ID-1: / size: 914.90 GiB used: 9.05 GiB (1.0%) fs: ext4 dev: /dev/sda5 
Sensors:
  System Temperatures: cpu: 41.0 C mobo: N/A gpu: nvidia temp: 37 C 
  Fan Speeds (RPM): N/A gpu: nvidia fan: 33% 
Repos:
  No active apt repos in: /etc/apt/sources.list 
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
  1: deb http://packages.linuxmint.com ulyssa main upstream import backport #id:linuxmint_main
  2: deb http://archive.ubuntu.com/ubuntu focal main restricted universe multiverse
  3: deb http://archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse
  4: deb http://archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse
  5: deb http://security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
  6: deb http://archive.canonical.com/ubuntu/ focal partner
Info:
  Processes: 270 Uptime: 8m Memory: 23.49 GiB used: 1.00 GiB (4.3%) 
  Init: systemd v: 245 runlevel: 5 Compilers: gcc: 9.3.0 alt: 9 Shell: bash 
  v: 5.0.17 running in: gnome-terminal inxi: 3.0.38
```

**Comment by kneekoo** [comment]
Fairly old PC but very nice specs, and nothing looks bad in this info. Post the output of this command:
```
dmesg -l warn,err,crit
```

Also, do the restarts happen under certain circumstances or after a certain amount of time, or it varies? And when the system crashes and reboots, is there any message on the screen that might help diagnose this issue? Take a photo if you can, and put it here.

**Comment by obxwindsurfer** [comment]
The restarts seem to occur within 10 min after login. To test, I just open a few accessories and wait. I have also encountered restarts when running the update manager.

Nothing is ever displayed on the screen when it crashes. The screen instantly goes black and then the reboot starts. Haven't noticed anything during reboot. I will try to catch any messages during reboot.

Here is the output from 'dmesg -l warn,err,crit' after a crash and reboot:

`[    0.229793] DMAR-IR: This system BIOS has enabled interrupt remapping
               on a chipset that contains an erratum making that
               feature unstable.  To maintain system stability
               interrupt remapping is being disabled.  Please
               contact your BIOS vendor for an update
[    0.364145] core: CPUID marked event: 'bus cycles' unavailable
[    0.375875] MDS CPU bug present and SMT on, data leak possible. See https://www.kernel.org/doc/html/latest/admin-guide/hw-vuln/mds.html for more details.
[    0.375875]   #5  #6  #7
[    0.392474] pmd_set_huge: Cannot satisfy [mem 0xf4000000-0xf4200000] with a huge-page mapping due to MTRR override.
[    0.466133] pci 0000:00:1c.0: ASPM: current common clock configuration is broken, reconfiguring
[    0.478674] pci 0000:00:1c.2: ASPM: current common clock configuration is broken, reconfiguring
[    0.490694] pci 0000:00:1c.4: ASPM: current common clock configuration is broken, reconfiguring
[    1.010307] i8042: Failed to disable AUX port, but continuing anyway... Is this a SiS?
[    1.010308] i8042: If AUX port is really absent please use the 'i8042.noaux' option
[    1.287277] platform eisa.0: EISA: Cannot allocate resource for mainboard
[    1.287279] platform eisa.0: Cannot allocate resource for EISA slot 1
[    1.287281] platform eisa.0: Cannot allocate resource for EISA slot 2
[    1.287283] platform eisa.0: Cannot allocate resource for EISA slot 3
[    1.287285] platform eisa.0: Cannot allocate resource for EISA slot 4
[    1.287286] platform eisa.0: Cannot allocate resource for EISA slot 5
[    1.287288] platform eisa.0: Cannot allocate resource for EISA slot 6
[    1.287290] platform eisa.0: Cannot allocate resource for EISA slot 7
[    1.287291] platform eisa.0: Cannot allocate resource for EISA slot 8
[    1.347986] usb 9-1: config 1 interface 0 altsetting 0 endpoint 0x81 has invalid wMaxPacketSize 0
[    1.877300] ACPI Warning: SystemIO range 0x0000000000000428-0x000000000000042F conflicts with OpRegion 0x000000000000042C-0x000000000000042D (\GP2C) (20190816/utaddress-204)
[    1.877328] lpc_ich: Resource conflict(s) found affecting gpio_ich
[    1.880386] r8169 0000:0a:00.0: can't disable ASPM; OS doesn't have ASPM control
[   17.792412] systemd-journald[404]: File /var/log/journal/43e2aab120174deeb6ae0b428b3f301a/system.journal corrupted or uncleanly shut down, renaming and replacing.
[   19.762359] kvm: VM_EXIT_LOAD_IA32_PERF_GLOBAL_CTRL does not work properly. Using workaround
[   21.053695] nvidia: loading out-of-tree module taints kernel.
[   21.053704] nvidia: module license 'NVIDIA' taints kernel.
[   21.053705] Disabling lock debugging due to kernel taint
[   21.191788] NVRM: loading NVIDIA UNIX x86_64 Kernel Module  455.38  Thu Oct 22 06:06:59 UTC 2020
[   28.443931] kauditd_printk_skb: 12 callbacks suppressed
[   32.988985] resource sanity check: requesting [mem 0x000e0000-0x000fffff], which spans more than pnp 00:04 [mem 0x000e0000-0x000effff]
[   32.989246] caller os_map_kernel_space.part.0+0x73/0x80 [nvidia] mapping multiple BARs
[   33.168283] resource sanity check: requesting [mem 0x000c0000-0x000fffff], which spans more than PCI Bus 0000:00 [mem 0x000c0000-0x000dffff window]
[   33.168489] caller os_map_kernel_space.part.0+0x73/0x80 [nvidia] mapping multiple BARs
[   62.136888] FAT-fs (sdb1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.`

**Comment by crossan007** [comment]
I think I'm having this issue as well on two different machines (Admittedly not running the 20.1-beta build)

```
System:    Kernel: 5.4.0-52-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Console: tty 1 Distro: Linux Mint 20 Ulyana 
           base: Ubuntu 20.04 focal 
Machine:   Type: Desktop System: Dell product: Precision T3610 v: 00 serial: <filter> 
           Mobo: Dell model: 09M8Y8 v: A01 serial: <filter> UEFI: Dell v: A18 date: 11/14/2018 
Battery:   Device-1: hidpp_battery_0 model: Logitech Wireless Mouse M310/M310t charge: 55% (should be ignored) 
           status: Discharging 
           Device-2: hidpp_battery_1 model: Logitech K520 charge: 70% (should be ignored) status: Discharging 
CPU:       Topology: 8-Core model: Intel Xeon E5-2650 v2 bits: 64 type: MT MCP arch: Ivy Bridge rev: 4 L2 cache: 20.0 MiB 
           flags: avx lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 83002 
           Speed: 2490 MHz min/max: 1200/3400 MHz Core speeds (MHz): 1: 2490 2: 2489 3: 2477 4: 2170 5: 2550 6: 2146 7: 2362 
           8: 2556 9: 2447 10: 2458 11: 2487 12: 2470 13: 2536 14: 2496 15: 2493 16: 2482 
Graphics:  Device-1: NVIDIA GM107GL [Quadro K620] vendor: Hewlett-Packard driver: nvidia v: 450.80.02 bus ID: 02:00.0 
           Display: server: X.org 1.20.8 driver: nvidia tty: 170x49 
           Message: Advanced graphics data unavailable in console. Try -G --display 
Audio:     Device-1: Intel C600/X79 series High Definition Audio vendor: Dell driver: snd_hda_intel v: kernel bus ID: 00:1b.0 
           Device-2: NVIDIA GM107 High Definition Audio [GeForce 940MX] vendor: Hewlett-Packard driver: snd_hda_intel 
           v: kernel bus ID: 02:00.1 
           Device-3: Logitech HD Webcam C910 type: USB driver: snd-usb-audio,uvcvideo bus ID: 2-1.6:4 
           Sound Server: ALSA v: k5.4.0-52-generic 
Network:   Device-1: Intel 82579LM Gigabit Network vendor: Dell driver: e1000e v: 3.2.6-k port: f040 bus ID: 00:19.0 
           IF: enp0s25 state: up speed: 1000 Mbps duplex: full mac: <filter> 
           IF-ID-1: br-283bfadfb82e state: up speed: N/A duplex: N/A mac: <filter> 
           IF-ID-2: br-9984d83c37aa state: down mac: <filter> 
           IF-ID-3: br-f8d8727a2a05 state: up speed: N/A duplex: N/A mac: <filter> 
           IF-ID-4: docker0 state: down mac: <filter> 
           IF-ID-5: tun0 state: unknown speed: 10 Mbps duplex: full mac: N/A 
           IF-ID-6: veth05e0883 state: up speed: 10000 Mbps duplex: full mac: <filter> 
           IF-ID-7: veth07caa96 state: up speed: 10000 Mbps duplex: full mac: <filter> 
           IF-ID-8: veth2974e2a state: up speed: 10000 Mbps duplex: full mac: <filter> 
           IF-ID-9: veth52e2b09 state: up speed: 10000 Mbps duplex: full mac: <filter> 
           IF-ID-10: veth6039111 state: up speed: 10000 Mbps duplex: full mac: <filter> 
           IF-ID-11: vethb328d5d state: up speed: 10000 Mbps duplex: full mac: <filter> 
Drives:    Local Storage: total: 3.86 TiB used: 1.31 TiB (33.9%) 
           ID-1: /dev/sda vendor: Crucial model: CT240BX500SSD1 size: 223.57 GiB 
           ID-2: /dev/sdb vendor: Western Digital model: WD2002FAEX-00MJRA0 size: 1.82 TiB 
           ID-3: /dev/sdc vendor: Western Digital model: WD2002FAEX-007BA0 size: 1.82 TiB 
RAID:      Device-1: tank type: zfs status: ONLINE size: 1.82 TiB free: 241.00 GiB Components: online: sdb 
Partition: ID-1: / size: 218.57 GiB used: 32.49 GiB (14.9%) fs: ext4 dev: /dev/sda2 
Sensors:   System Temperatures: cpu: 45.0 C mobo: 46.0 C sodimm: 44.0 C 
           Fan Speeds (RPM): cpu: 1002 
Info:      Processes: 526 Uptime: 1h 24m Memory: 15.58 GiB used: 3.48 GiB (22.4%) Init: systemd runlevel: 5 Compilers: 
           gcc: 9.3.0 Shell: bash v: 5.0.17 inxi: 3.0.38
```

```
System:    Host: media-desktop Kernel: 4.15.0-122-generic x86_64 (64 bit gcc: 5.4.0) Console: tty 5
           Distro: Linux Mint 18.2 Sonya
Machine:   Mobo: ASRock model: Z97 Extreme4 Bios: American Megatrends v: P2.10 date: 05/12/2015
CPU:       Quad core Intel Core i7-4790K (-HT-MCP-) cache: 8192 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 31991
           clock speeds: max: 4000 MHz 1: 3998 MHz 2: 3998 MHz 3: 3998 MHz 4: 3998 MHz 5: 3998 MHz 6: 3998 MHz
           7: 3998 MHz 8: 3998 MHz
Graphics:  Card: Intel Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller bus-ID: 00:02.0
           Display Server: N/A drivers: intel (unloaded: fbdev,vesa) tty size: 189x57 Advanced Data: N/A out of X
Audio:     Card-1 Intel Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller bus-ID: 00:03.0
           Card-2 Intel 9 Series Family HD Audio Controller driver: snd_hda_intel bus-ID: 00:1b.0
           Sound: Advanced Linux Sound Architecture v: k4.15.0-122-generic
Network:   Card-1: Intel Ethernet Connection (2) I218-V driver: e1000e v: 3.2.6-k port: f060 bus-ID: 00:19.0
           IF: enp0s25 state: up speed: 1000 Mbps duplex: full mac: <filter>
           Card-2: Realtek RTL8192CE PCIe Wireless Network Adapter driver: rtl8192ce port: d000 bus-ID: 04:00.0
           IF: wlp4s0 state: down mac: <filter>
Drives:    HDD Total Size: 240.1GB (37.1% used) ID-1: /dev/sda model: KINGSTON_SV300S3 size: 240.1GB
Partition: ID-1: / size: 205G used: 68G (36%) fs: ext4 dev: /dev/sda1
           ID-2: swap-1 size: 16.85GB used: 0.14GB (1%) fs: swap dev: /dev/sda5
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 47.0C mobo: N/A gpu: 0.0:
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 229 Uptime: 6 days Memory: 2432.1/15734.5MB Init: systemd runlevel: 5 Gcc sys: 5.4.0
           Client: Shell (bash 4.3.481) inxi: 2.2.35
```

**Comment by obxwindsurfer** [comment]
I think I may have discovered the problem and at least a temporary solution. This was previously reported for Ubuntu 20.04.

According to the dmesg output, interrupt remapping is being disabled due to an Intel hardware bug, but it appears it is not. Explicitly turning off interrupt remapping in the grub configuration file looks like it fixes the problem. Here is the solution:

Edit /etc/default/grub
Change the line: `GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"` to
`GRUB_CMDLINE_LINUX_DEFAULT="intremap=off quiet splash"`
Run `sudo update-grub`
Restart

It is not clear why the Intel hardware bug was properly handled in other releases, but not for Mint 20 or apparently Ubuntu 20.

**Comment by crossan007** [comment]
@obxwindsurfer nice!  I'm hopeful this will work.

Can you share the link you found to support this, or at least the lines from dmesg which indicate the scenario?

**Comment by obxwindsurfer** [comment]
Here is the link where I found the discussion of this solution:
[https://askubuntu.com/questions/1266668/ubuntu-20-04-very-slow-boot-drmdrm-atomic-helper-wait-for-dependencies-drm-km](url)

**Comment by obxwindsurfer** [comment]
The first lines from dmesg as listed above point to my particular problem.
`[ 0.229793] DMAR-IR: This system BIOS has enabled interrupt remapping on a chipset that contains an erratum making that feature unstable. To maintain system stability interrupt remapping is being disabled. Please contact your BIOS vendor for an update`
My BIOS does not allow the interrupt remapping to be disabled. It is strange, but I never encountered this problem previously.

**Comment by SimonIremonger** [comment]
Tried upgrading the BIOS/UEFI firmware, in any case? .....

**Comment by obxwindsurfer** [comment]
I am using the last official BIOS release for my motherboard: Gigabyte model: X58A-UD3R Rev 1.0, BIOS: F6 date: 08/24/2010. Later releases were beta versions supporting larger capacity hard drives. I do not have enough confidence in the beta BIOS versions to risk trying them.

**Comment by clefebvre** [comment]
I'll close this here since it's upstream and not BETA specific.

Let's continue the troubleshooting on https://github.com/linuxmint/linuxmint/issues/306.
