### ISSUE TITLE
Translations: cinnamon display settings, dialog is not translated.

### ISSUE THREAD

**Issue by Boored-Dude** [linuxmint/mint20.1-beta#25]
The Dialog to confirm the new configuration appears to have no translation.
Switching to another German Language (German, Switzerland oder German, Belgium) shows the same result. No Translation of the "Confirm New Configuration" Dialog.

The same results show after switching to France and Italian Language (all necessary packets installed).

Mint 20.1 Beta Cinnamon - German

![2020-12-20_M20_1_cin_Monitor_translation](https://user-images.githubusercontent.com/73738499/102709829-340de280-42ae-11eb-9671-b813cb31be36.PNG)

**Comment by mtwebster** [comment]
The dialog is coming from a different program than the settings window. Did you log out and back in after changing languages?

Run the following:
```
sudo killall csd-xrandr
sudo killall csd-xrandr
csd-xrandr --verbose
```
Then change the display settings to bring up that dialog - is it translated?

**Comment by Boored-Dude** [comment]
After changing the the language i did first logout, then login and then change the display settings.
The Dialog was not translated.

To test the things you sugested, i first did install the latest updates from the official repos and then rebooted the machine.
After that logged in, changed the language to french, logged out and logged in again.
I did run the commands in a terminal and after that changed the display settings.
The dialog was not translated.
The output of the last command is in the attached file.
[Output xrandr_verbose.txt](https://github.com/linuxmint/mint20.1-beta/files/5736210/Output.xrandr_verbose.txt)

[edit]
Even rebooting after changing the language has the same result: dialog is not translated.

**Comment by clefebvre** [comment]
I can reproduce it.
