### ISSUE TITLE
App Calendar - add/import new calendar - maybe Upstream(?)

### ISSUE THREAD

**Issue by Boored-Dude** [linuxmint/mint20.1-beta#26]
When adding/importing an Calendar from a web/webdav source, the app will crash to the desktop as soon a you type the "**:**" after http or https or paste the string "http:" or "https:" or even "abcd:".

Some tests show this error triggers if the entire font width of the inserted text falls below the width of "123456" and then it is no matter where you insert the ":". The App will crash to the Desktop.

**Comment by Boored-Dude** [comment]
Adding some logfiles and inxi-output
[inxi.txt](https://github.com/linuxmint/mint20.1-beta/files/5720878/inxi.txt)
[Snapshot_Coredump_journal_crash_calendar.txt](https://github.com/linuxmint/mint20.1-beta/files/5720879/Snapshot_Coredump_journal_crash_calendar.txt)

[Protokollmeldungen_system.txt](https://github.com/linuxmint/mint20.1-beta/files/5720880/Protokollmeldungen_system.txt)

**Comment by xenopeek** [comment]
This isn't a beta issue; the same happens on Ubuntu 20.04 when I tested it. I think you should report this upstream at https://gitlab.gnome.org/GNOME/gnome-calendar/-/issues so the Calendar developers can look at it.

Before you report a new issue there please see if there are any related issues (at first glance I didn't spot any). Then before you report it get a stack trace from the crash with debug symbols installed else the Calendar developers have not enough information to go on.

The steps for this are as follows:

1. First run command `apt install gnome-calendar/focal` to downgrade Calendar to the Ubuntu 20.04 version (mandatory for next steps to work).
2. Open Software Sources and enable debug symbols on the official repositories tab. Refresh the repository cache as prompted.
3. Then run `apt install debian-goodies` on the terminal to install a necessary package for the next step.
4. Then run `find-dbgsym-packages /usr/bin/gnome-calendar` to find all needed debug symbol packages. This command can take a bit of time. It will probably show some packages it can't find and finally a long list of packages it could find.
5. Then run `apt install copied-list-from-step-4-here` (replace "copied-list-from-step-4-here" with the actual list) to install all the debug symbol packages found at step 4.
6. After all are installed make sure Calendar is closed and then start it from the terminal as such:
```
gdb -q -ex 'set logging on' -ex 'set pagination off' -ex 'thread apply all backtrace' -ex 'run' gnome-calendar
```
7. The program will probably load slower and it may look like it's not doing anything for a bit. Once the window is open redo the steps to make it crash; after entering "http:" for the calendar to add the window will freeze. Return to the terminal and you will see debug output there. Type "quit" on the (gdb) prompt and press enter key to close gdb. It will ask if it is okay to kill the running program, that's okay.
8. You will now have a gdb.txt file with the backtrace with debug symbols. Attach this to the issue.

After you've done all that you can remove the debug symbol packages if you want. With the list of packages from step 4 run the command `apt purge copied-list-from-step-4-here`. You can also uninstall the debian-goodies package if you want. To re-upgrade to the Linux Mint 20.1 version of Calendar simply run `apt install gnome-calendar`.
