### ISSUE TITLE
Cursor behaviour when starting Redshift

### ISSUE THREAD

**Issue by jakoblm** [linuxmint/mint20.1-beta#28]
Dear Mint Team, 

Linux Mint 20.1 Cinnamon: The mouse cursor still rotates when starting Redshift. I had already created a bug report about this a few months ago: https://github.com/linuxmint/cinnamon/issues/9633 

Is it possible to fix the problem until the release of Mint 20.1?

**Comment by mtwebster** [comment]
Hi, can you try something:

Copy the file `/usr/share/applications/redshift-gtk.desktop` to `~/.local/share/applications`
```
cp /usr/share/applications/redshift-gtk.desktop ~/.local/share/applications
```

Then open that file with the text editor, and the very last line should read `StartupNotify=true` - comment that out by putting a # in front of it:
```
# StartupNotify=true
```
Then see if the icon still changes.

**Comment by jakoblm** [comment]
This seems to work! I have tested it in **LMDE 4** and **Linux Mint 20.1** (Live System). 
After copying and editing the file, I had to recreate the autostart entry in LMDE 4 to start Redshift automatically at system startup. 
In Linux Mint 20.1 I had to create the `~/.local/share/applications` folder first before I could copy the file.

**Comment by clefebvre** [comment]
Fixed.

**Comment by jakoblm** [comment]
Thank you! Does this mean that I can undo this workaround in LMDE 4? Will it be automatically integrated in Linux Mint 20, 20.1 and LMDE 4 after the release?
