### ISSUE TITLE
Cinnamon OSD volume control shows 101%

### ISSUE THREAD

**Issue by quicoa** [linuxmint/mint20.1-beta#34]
When controlling the volume with keyboard shortcuts, the on-screen display shows 101% when hitting the maximum volume (amplification is disabled, like the default is). When hovering over the sound applet in the bottom-right corner it still shows 100%. This looks like a bug since the OSD shows something different than the actual value.
To reproduce:
Tested in VirtualBox (6.0.24) with VBoxVGA as graphics controller (maybe that's a factor, I don't know).
Load up the liveCD 
Go to keyboard shortcuts and set the volume up & down to something like CTRL++ and CTRL+- (might not be necessary)
Use and hold the volume up shortcut to turn the volume up until it reaches 101%

It is not an annoying bug, but it's probably not the way it should behave.
Hope this helps anyone fixing this

**Comment by MrEen-Mint** [comment]
If you volume down until it reaches 0% then raise it all the way again, does that make it stop at 100%? And if not, was 100% shown before it went to 101%?

I ask because the default settings are increments/decrements of 5%, and maybe if the starting volume integer is not a multiple of 5 nor 0 that might cause this.

**Comment by quicoa** [comment]
> If you volume down until it reaches 0% then raise it all the way again, does that make it stop at 100%? And if not, was 100% shown before it went to 101%?

If I volume down until 0% and then hold volume up it goes to 95%, 100% en then to 101%. You can stop at 100%, but that's not the maximum. It makes no difference if the volume is set from 100% to 95% and back to 100%, after volume up at 100%, it says 101%, while the _actual_ value is no more than 100%. Just try it in a VM, if you have the ISO.

**Comment by MrEen-Mint** [comment]
I can't really test as Cinnamon doesn't play nicely with my old hardware. 

I was just trying to help pinpoint where the issue might lie for those that can do something about it.

And to mention something even weirder, just today there was a post in the forum about the OSD displaying 1% **less** than the actual volume on a previous version of Cinnamon.

**Comment by quicoa** [comment]
Good job fixing it so fast!
