### ISSUE TITLE
unable to use as hotspot

### ISSUE THREAD

**Issue by D-EVE-R** [linuxmint/mint20.1-beta#36]
this issue's on 20 and not 19.3 but unfortunately, it's present on 20.1 too, which I cant use as a hotspot from network settings (graphic method) the only option to solve it is by using a command line on the terminal 
20.1
![Screenshot from 2020-12-20 22-00-00](https://user-images.githubusercontent.com/66891134/102725886-68b78380-431a-11eb-8b1f-83a8bfbe0415.png)
20
![Screenshot from 2020-12-20 23-22-49](https://user-images.githubusercontent.com/66891134/102725887-6a814700-431a-11eb-80e8-317e16928766.png)

**Comment by icarter09** [comment]
Verified this issue exists on both Mint 20 and Mint 20.1

@D-EVE-R feel free to close this ticket and reopen the issue in the Cinnamon repo. Thanks.

**Comment by icarter09** [comment]
@D-EVE-R you must be root in order to enable a device as a Hotspot through the GUI. I was able to verify this by logging in as root and running `cinnamon-settings` via the terminal. "Use as Hotspot" should be enabled.

**Comment by D-EVE-R** [comment]
> @D-EVE-R you must be root in order to enable a device as a Hotspot through the GUI. I was able to verify this by logging in as root and running `cinnamon-settings` via the terminal, then `Network`. "Use as Hotspot" should be enabled. Verified on both Mint 20 and Mint 20.1 beta.

oh thanks for your reply I got it

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/cinnamon-control-center/commit/b225e86fed2bc565e83c98386eba7bf645051849.
