### ISSUE TITLE
Video display distorded - Mate

### ISSUE THREAD

**Issue by Computersleuth** [linuxmint/mint20.1-beta#37]
On Mate, when the ISO is booted in normal mode via DVD, the display is totally distorted.  The display appears to be out of sync with the video card and/or main memory.  This bug also exists in Mint/Mate 20.0.

In researching this, I removed several hardware components from my system (video card, memory module, etc) before finding that Cinnamon boots and runs correctly, whereas Mate fails.  To me, It appears that some aspect of the Mate software is writing into memory that's (directly or indirectly) accessed for video display; however, the symptoms are the same whether a video card is inserted, or on-board video is used. (the MB has its own video firmware).

**Comment by Jildridge** [comment]
This issue is obviously Mate-related, mainly affecting AMD GPUs. The same problem is to be found with xfce desktop. And it is not limited to Linux mint. Here you can find further discussions and workarounds:
https://ubuntu-mate.community/t/20-04-display-issues-with-amd-gpu/21648

In Linux Mint you should turn off Macro+Compositing in the windows manager, using another option like Compton or Metacity.
Therefore you need to start Mint-Mate live under fail-safe conditions, and then install it. After installation, you need to reboot again in fail safe mode; now change the a.m. options in windows manager. After next reboot Mint Mate should start properly in normal mode.

**Comment by clefebvre** [comment]
You can use the console to restart another window manager:

- `Ctrl+Alt+F2` (switches to console)
- Login with the `mint` username and no password (just press enter if asked for a password)
- `export DISPLAY=:0.0` (allows the console to access your graphical session)
- `marco --no-composite --replace` (to kill the window manager and restart it without compositing)
- `Ctrl+Alt+F7` (to go back to your graphical session)

Then install Mint, use the same trick post-install if needed (but with your new username/password).

And finally launch `Desktop Settings` from the menu and switch to another Window Manager (Metacity, Compton, Compiz..etc) or one without compositing.

**Comment by clefebvre** [comment]
Many thanks @Jildridge for the pertinent info. I'll close this @Computersleuth as it's not something we can tackle during the BETA.

**Comment by Computersleuth** [comment]
Hi Clem,

Thanks so much for looking at this.  When I posted it, I didn't see the ticket that was previously recorded.

Nonetheless, please note that this failure doesn't happen with all AMD CPUs.  Indeed, one of my AMD systems works fine.

Again, thanks,
  - Dave Jewett



------- Original Message -------
From    : Clement Lefebvre[mailto:notifications@github.com]
Sent    : 12/31/2020 8:54:38 AM
To      : mint20.1-beta@noreply.github.com
Cc      : dave.jewett@outdrs.net; author@noreply.github.com
Subject : RE: Re: [linuxmint/mint20.1-beta] Video display distorded - Mate (#37)

 
You can use the console to restart another window manager:

Ctrl+Alt+F2 (switches to console)
Login with the mint username and no password (just press enter if asked for a password)
export DISPLAY=:0.0 (allows the console to access your graphical session)
marco --no-composite --replace (to kill the window manager and restart it without compositing)
Ctrl+Alt+F7 (to go back to your graphical session)

Then install Mint, use the same trick post-install if needed (but with your new username/password).
And finally launch Desktop Settings from the menu and switch to another Window Manager (Metacity, Compton, Compiz..etc) or one without compositing.
