### ISSUE TITLE
codecs: Error installing multimedia codecs offline

### ISSUE THREAD

**Issue by lin141** [linuxmint/mint20.1-beta#47]
![Peek 2020-12-22 13-07](https://user-images.githubusercontent.com/76395492/102891825-c9e47180-4456-11eb-8deb-95bd22ed8c15.gif)
I came back with some details about this error after downloading the multimedia codecs package from the linux terminal and installing it ... the first error is
![Peek 2020-12-22 12-45](https://user-images.githubusercontent.com/76395492/102891039-74f42b80-4455-11eb-97ba-6bb38f95b512.gif)and the second problem is that I can no longer install any program in the software manager gives me the following error, please fix the multimedia codecs package, thank you ...
![Peek 2020-12-22 12-42](https://user-images.githubusercontent.com/76395492/102891291-d87e5900-4455-11eb-9985-ec93556f7d6d.gif)

**Comment by clefebvre** [comment]
Thanks, we'll try to reproduce and fix this.

**Comment by clefebvre** [comment]
Fixed in mintsystem 8.5.1. https://github.com/linuxmint/mintsystem/commit/8782df0fd8e43f249351bcdd4654dbec36b53b00
