### ISSUE TITLE
nvidia: Low resolution after account switch

### ISSUE THREAD

**Issue by Waper77** [linuxmint/mint20.1-beta#48]
LinuxMint 20.1 beta has the same problem as version 20. Therefore, I will paste the content of a forum post about LinuxMint.
https://forums.linuxmint.com/viewtopic.php?f=90&t=336834&p=1938292#p1938292
"On nvidia proprietary drivers everything works fine until I try to switch to the other user account. This means: When I log out of my account and log in to the other one, that's ok. Unfortunately, when instead of logging out I just want to switch, the screen resolution drops to a very low level. After logging into the second account, the resolution is still very low and a crash message appears. When I return to my account, the resolution returns to normal (in my case, fullhd). There is no problem with this on open source drivers (...) My account is an administrator account. The second account is the standard user. This appears immediately after clicking "switch user" ... I don't even need to enter the second account (and only on proprietary drivers)".
This is not just a specific desktop environment problem. I use Cinnamon, but XFCE is the same.

**Comment by rank-coder** [comment]
I have also seen this issue in LM 20 Cinnamon.

**Comment by clefebvre** [comment]
Does it happen if the second account is an admin account as well?

**Comment by Waper77** [comment]
I just checked. It's the same. Just click "switch user" and the screen resolution drops.

**Comment by clefebvre** [comment]
This is a recently installed Mint right? Not an upgraded one? I ask this because I saw somebody in the forum thread mention mdm...

**Comment by Waper77** [comment]
Yes, it's a fresh install on a blank disk.

**Comment by clefebvre** [comment]
I can't reproduce it here but I'm on a 1660ti with NVIDIA 455.. you're on a really old GPU (9800) with legacy 340 drivers.. 

This looks upstream to me. I would suggest to ask NVIDIA directly.
