### ISSUE TITLE
Cannot scoll in hypnotix channel list with keyboard

### ISSUE THREAD

**Issue by mirohh-commits** [linuxmint/mint20.1-beta#50]
If i opened a country i.e.germany, i see 6 channels on the left.  There are 29 Channels online. i am unable to scroll down with the keybord on the left side.. With the mouse it works.I have a dell laptop. resolution is set to 1600 * 900.
cu MiRo

**Comment by icarter09** [comment]
Verified that this issue occurs with all selections and happens on Mint 20 as well. Not an issue with Mint 20.1, but rather a feature request/issue with the Hypnotix UI. This issue could be closed and reopened in the Hypnotix repo.

**Comment by mirohh-commits** [comment]
moved to HyPNOTIX
