### ISSUE TITLE
Folder color switcher (nemo extension) not show on context menu

### ISSUE THREAD

**Issue by stephanelorrain** [linuxmint/mint20.1-beta#52]
The **Nemo** extension "**Folder color switcher**" seams to be installed, but I don't see the option anywhere in the context menu.
However, if instead I install `folder-color-nemo` from repository `ppa:costales/folder-color`, this one works.

**Comment by xenopeek** [comment]
Nemo's folder color switcher works with supported icon themes. Mint-X and Mint-Y themes for example. With a supported icon theme in use the context menu shows as such to switch folder color:

![image](https://user-images.githubusercontent.com/21159972/103150842-3ec9eb00-4778-11eb-9a9f-a1138e635acc.png)

**Comment by stephanelorrain** [comment]
Thanks! Now I understand.
