### ISSUE TITLE
Pinta unstable and crashes

### ISSUE THREAD

**Issue by networkinss** [linuxmint/mint20.1-beta#53]
Hello, Pinta is unstable and crashes after about 1 minute.
The time to crash varies, can be sooner or later than 1 min.

It either closes without action from user or freezes (with action change image size).

Here the crash report:

===================================================================
 Info                                                              
===================================================================
           PID: 8256 (mono)
           UID: 1000 (amrit)
           GID: 1000 (amrit)
        Signal: 6 (ABRT)
     Timestamp: Sat 2020-12-26 08:22:44 CET (44min ago)
  Command Line: /usr/bin/mono /usr/lib/pinta/Pinta.exe
    Executable: /usr/bin/mono-sgen
 Control Group: /user.slice/user-1000.slice/user@1000.service/dbus.service
          Unit: user@1000.service
     User Unit: dbus.service
         Slice: user-1000.slice
     Owner UID: 1000 (amrit)
       Boot ID: b2e7f17972044e65b691f2f85e556a19
    Machine ID: 026c3d8aef5546739c50e4de8698ce05
      Hostname: tplm
       Storage: /var/lib/systemd/coredump/core.mono.1000.b2e7f17972044e65b691f2f85e556a19.8256.1608967364000000000000.lz4
       Message: Process 8256 (mono) of user 1000 dumped core.
                
                Stack trace of thread 8260:
                #0  0x00007fd2e4c7e18b __GI_raise (libc.so.6 + 0x4618b)
                #1  0x00007fd2e4c5d859 __GI_abort (libc.so.6 + 0x25859)
                #2  0x000055b2ca4c66ca n/a (mono-sgen + 0x2c6ca)
                #3  0x000055b2ca5041bd n/a (mono-sgen + 0x6a1bd)
                #4  0x000055b2ca556467 n/a (mono-sgen + 0xbc467)
                #5  0x00007fd2e4e5a3c0 __restore_rt (libpthread.so.0 + 0x153c0)
                #6  0x00007fd2e4c7e18b __GI_raise (libc.so.6 + 0x4618b)
                #7  0x00007fd2e4c5d859 __GI_abort (libc.so.6 + 0x25859)
                #8  0x00007fd2e4cc83ee __libc_message (libc.so.6 + 0x903ee)
                #9  0x00007fd2e4cd047c malloc_printerr (libc.so.6 + 0x9847c)
                #10 0x00007fd2e4cd06cc munmap_chunk (libc.so.6 + 0x986cc)
                #11 0x0000000041ac9633 n/a (n/a + 0x0)
                #12 0x0000000041ac6dcd n/a (n/a + 0x0)
                #13 0x000055b2ca7511c4 n/a (mono-sgen + 0x2b71c4)
                #14 0x000055b2ca77e60c n/a (mono-sgen + 0x2e460c)
                #15 0x000055b2ca751a74 n/a (mono-sgen + 0x2b7a74)
                #16 0x000055b2ca6fef3a n/a (mono-sgen + 0x264f3a)
                #17 0x00007fd2e4e4e609 start_thread (libpthread.so.0 + 0x9609)
                #18 0x00007fd2e4d5a293 __clone (libc.so.6 + 0x122293)
                
                Stack trace of thread 8256:
                #0  0x00007fd2e4d4daff __GI___poll (libc.so.6 + 0x115aff)
                #1  0x00007fd2e07cf1ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007fd2e07cf533 g_main_loop_run (libglib-2.0.so.0 + 0x52533)
                #3  0x00007fd2e1011092 gtk_main (libgtk-x11-2.0.so.0 + 0x13b092)
                #4  0x0000000041aae920 n/a (n/a + 0x0)
                #5  0x000000004195d9c2 n/a (n/a + 0x0)
                #6  0x000055b2ca4d1712 n/a (mono-sgen + 0x37712)
                #7  0x000055b2ca6d14ce n/a (mono-sgen + 0x2374ce)
                #8  0x000055b2ca6d482f n/a (mono-sgen + 0x23a82f)
                #9  0x000055b2ca4d7123 mono_jit_exec (mono-sgen + 0x3d123)
                #10 0x000055b2ca4d89f2 mono_main (mono-sgen + 0x3e9f2)
                #11 0x000055b2ca4c73fc n/a (mono-sgen + 0x2d3fc)
                #12 0x00007fd2e4c5f0b3 __libc_start_main (libc.so.6 + 0x270b3)
                #13 0x000055b2ca4c7b8e _start (mono-sgen + 0x2db8e)
                
                Stack trace of thread 8261:
                #0  0x00007fd2e4d4daff __GI___poll (libc.so.6 + 0x115aff)
                #1  0x00007fd2e07cf1ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007fd2e07cf2e3 g_main_context_iteration (libglib-2.0.so.0 + 0x522e3)
                #3  0x00007fd2e07cf331 n/a (libglib-2.0.so.0 + 0x52331)
                #4  0x00007fd2e07f8931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007fd2e4e4e609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007fd2e4d5a293 __clone (libc.so.6 + 0x122293)
                
                Stack trace of thread 8262:
                #0  0x00007fd2e4d4daff __GI___poll (libc.so.6 + 0x115aff)
                #1  0x00007fd2e07cf1ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007fd2e07cf533 g_main_loop_run (libglib-2.0.so.0 + 0x52533)
                #3  0x00007fd2e0a8ceda n/a (libgio-2.0.so.0 + 0x11eeda)
                #4  0x00007fd2e07f8931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007fd2e4e4e609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007fd2e4d5a293 __clone (libc.so.6 + 0x122293)
                
                Stack trace of thread 8284:
                #0  0x00007fd2e4d5389d syscall (libc.so.6 + 0x11b89d)
                #1  0x00007fd2e081c5a6 g_cond_wait_until (libglib-2.0.so.0 + 0x9f5a6)
                #2  0x00007fd2e079f561 n/a (libglib-2.0.so.0 + 0x22561)
                #3  0x00007fd2e079fb86 g_async_queue_timeout_pop (libglib-2.0.so.0 + 0x22b86)
                #4  0x00007fd2e07f9279 n/a (libglib-2.0.so.0 + 0x7c279)
                #5  0x00007fd2e07f8931 n/a (libglib-2.0.so.0 + 0x7b931)
                #6  0x00007fd2e4e4e609 start_thread (libpthread.so.0 + 0x9609)
                #7  0x00007fd2e4d5a293 __clone (libc.so.6 + 0x122293)
                
                Stack trace of thread 8259:
                #0  0x00007fd2e4e55376 futex_wait_cancelable (libpthread.so.0 + 0x10376)
                #1  0x000055b2ca7abdc6 n/a (mono-sgen + 0x311dc6)
                #2  0x00007fd2e4e4e609 start_thread (libpthread.so.0 + 0x9609)
                #3  0x00007fd2e4d5a293 __clone (libc.so.6 + 0x122293)
===================================================================
 GDB Log                                                           
===================================================================

warning: core file may not match specified executable file.
[New LWP 8260]
[New LWP 8256]
[New LWP 8261]
[New LWP 8262]
[New LWP 8284]
[New LWP 8259]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/bin/mono /usr/lib/pinta/Pinta.exe'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7fd2e1c87700 (LWP 8260))]

===================================================================
 GDB Backtrace                                                     
===================================================================

warning: core file may not match specified executable file.
[New LWP 8260]
[New LWP 8256]
[New LWP 8261]
[New LWP 8262]
[New LWP 8284]
[New LWP 8259]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/bin/mono /usr/lib/pinta/Pinta.exe'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7fd2e1c87700 (LWP 8260))]
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fd2e4c5d859 in __GI_abort () at abort.c:79
#2  0x000055b2ca4c66ca in ?? ()
#3  0x000055b2ca5041bd in ?? ()
#4  0x000055b2ca556467 in ?? ()
#5  <signal handler called>
#6  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#7  0x00007fd2e4c5d859 in __GI_abort () at abort.c:79
#8  0x00007fd2e4cc83ee in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7fd2e4df2285 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#9  0x00007fd2e4cd047c in malloc_printerr (str=str@entry=0x7fd2e4df41e0 "munmap_chunk(): invalid pointer") at malloc.c:5347
#10 0x00007fd2e4cd06cc in munmap_chunk (p=<optimized out>) at malloc.c:2830
#11 0x0000000041ac9633 in ?? ()
#12 0x000055b2cce27950 in ?? ()
#13 0x00007fd2e1c86ca0 in ?? ()
#14 0x000055b2cc4bdde0 in ?? ()
#15 0x0000000000000000 in ?? ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================

warning: core file may not match specified executable file.
[New LWP 8260]
[New LWP 8256]
[New LWP 8261]
[New LWP 8262]
[New LWP 8284]
[New LWP 8259]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/bin/mono /usr/lib/pinta/Pinta.exe'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7fd2e1c87700 (LWP 8260))]

Thread 6 (Thread 0x7fd2e3fff700 (LWP 8259)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55b2ca948e08) at ../sysdeps/nptl/futex-internal.h:183
        __ret = -512
        oldtype = 0
        err = <optimized out>
        oldtype = <optimized out>
        err = <optimized out>
        __ret = <optimized out>
        resultvar = <optimized out>
        __arg4 = <optimized out>
        __arg3 = <optimized out>
        __arg2 = <optimized out>
        __arg1 = <optimized out>
        _a4 = <optimized out>
        _a3 = <optimized out>
        _a2 = <optimized out>
        _a1 = <optimized out>
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55b2ca948e20, cond=0x55b2ca948de0) at pthread_cond_wait.c:508
        spin = 0
        buffer = {__routine = 0x7fd2e4e55050 <__condvar_cleanup_waiting>, __arg = 0x7fd2e3ffede0, __canceltype = -469766668, __prev = 0x0}
        cbuffer = {wseq = 0, cond = 0x55b2ca948de0, mutex = 0x55b2ca948e20, private = 0}
        err = <optimized out>
        g = 0
        flags = <optimized out>
        g1_start = <optimized out>
        signals = <optimized out>
        result = 0
        wseq = 0
        seq = 0
        private = <optimized out>
        maxspin = <optimized out>
        err = <optimized out>
        result = <optimized out>
        wseq = <optimized out>
        g = <optimized out>
        seq = <optimized out>
        flags = <optimized out>
        private = <optimized out>
        signals = <optimized out>
        g1_start = <optimized out>
        spin = <optimized out>
        buffer = <optimized out>
        cbuffer = <optimized out>
        s = <optimized out>
#2  __pthread_cond_wait (cond=0x55b2ca948de0, mutex=0x55b2ca948e20) at pthread_cond_wait.c:638
No locals.
#3  0x000055b2ca7abdc6 in ?? ()
No symbol table info available.
#4  0x00007fd2e4e4e609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140543745062656, -1347485929389826072, 140721820741198, 140721820741199, 140721820741200, 140543745060736, 1362624006055911400, 1362635095965687784}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#5  0x00007fd2e4d5a293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 5 (Thread 0x7fd2c67fc700 (LWP 8284)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
No locals.
#1  0x00007fd2e081c5a6 in g_cond_wait_until () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007fd2e079f561 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007fd2e079fb86 in g_async_queue_timeout_pop () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007fd2e07f9279 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007fd2e07f8931 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#6  0x00007fd2e4e4e609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140543250122496, -1347485929389826072, 140721820726894, 140721820726895, 140721820727040, 140543250120576, 1362699873968840680, 1362635095965687784}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#7  0x00007fd2e4d5a293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 4 (Thread 0x7fd2db2ad700 (LWP 8262)):
#0  0x00007fd2e4d4daff in __GI___poll (fds=0x55b2cc7eb890, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007fd2e07cf1ae in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007fd2e07cf533 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007fd2e0a8ceda in ?? () from /lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#4  0x00007fd2e07f8931 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007fd2e4e4e609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140543596877568, -1347485929389826072, 140721820735662, 140721820735663, 140721820735808, 140543596875648, 1362746780917293032, 1362635095965687784}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007fd2e4d5a293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 3 (Thread 0x7fd2dbaae700 (LWP 8261)):
#0  0x00007fd2e4d4daff in __GI___poll (fds=0x55b2cc7bddc0, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007fd2e07cf1ae in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007fd2e07cf2e3 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007fd2e07cf331 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007fd2e07f8931 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007fd2e4e4e609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140543605270272, -1347485929389826072, 140721820735230, 140721820735231, 140721820735376, 140543605268352, 1362747879892049896, 1362635095965687784}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007fd2e4d5a293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 2 (Thread 0x7fd2e4c33780 (LWP 8256)):
#0  0x00007fd2e4d4daff in __GI___poll (fds=0x55b2ccf3a480, nfds=3, timeout=500) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007fd2e07cf1ae in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007fd2e07cf533 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007fd2e1011092 in gtk_main () from /lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
No symbol table info available.
#4  0x0000000041aae920 in ?? ()
No symbol table info available.
#5  0x000055b2cc511410 in ?? ()
No symbol table info available.
#6  0x000055b2cc4c1d98 in ?? ()
No symbol table info available.
#7  0x00007fd2e4000aa8 in ?? ()
No symbol table info available.
#8  0x00007fd2e4003c30 in ?? ()
No symbol table info available.
#9  0x00007fd2e4003c80 in ?? ()
No symbol table info available.
#10 0x000055b2cc4dc970 in ?? ()
No symbol table info available.
#11 0x00007ffc5a232eb0 in ?? ()
No symbol table info available.
#12 0x00007ffc5a232d50 in ?? ()
No symbol table info available.
#13 0x0000000000000000 in ?? ()
No symbol table info available.

Thread 1 (Thread 0x7fd2e1c87700 (LWP 8260)):
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 73746577110075911, 2019317000639164443, 2097844112522096650, 878203026951315226, 0, 0, 1536, 35184376905838, 2378464515277717504, 20655425439924491, 845850859291984, 0, 0, 0, 4}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007fd2e4c5d859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0, 140543707863616, 140543707863576, 0, 1536, 35184376905838, 2378464515277717504, 20655425439924491, 845850859291984, 0, 0, 0, 11812123812155645952, 94226421971376, 140543707870976, 94226389866757}}, sa_flags = -506961856, sa_restorer = 0x7fd2e1c86330}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x000055b2ca4c66ca in ?? ()
No symbol table info available.
#3  0x000055b2ca5041bd in ?? ()
No symbol table info available.
#4  0x000055b2ca556467 in ?? ()
No symbol table info available.
#5  <signal handler called>
No locals.
#6  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 94222992539649, 94226420063712, 0, 0, 1100686480, 7419270586075662814, 10037679144244668560, 94222992605183, 11812123812155645952, 94226426129856, 94226426130256, 94226426129856, 0, 1100685776, 94226386814194}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#7  0x00007fd2e4c5d859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x7fd2dc001338, sa_sigaction = 0x7fd2dc001338}, sa_mask = {__val = {11812123812155645952, 1101826208, 94226429933904, 140543707868000, 94226388844780, 94226420063712, 11812123812155645952, 94226429933904, 1087594561, 140543610856901, 140543707867776, 140543707868016, 140543707867560, 140543610854752, 140543551985456, 8}}, sa_flags = -603974912, sa_restorer = 0x55b2cce27950}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#8  0x00007fd2e4cc83ee in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7fd2e4df2285 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
        ap = {{gp_offset = 24, fp_offset = 21938, overflow_arg_area = 0x7fd2e1c86af0, reg_save_area = 0x7fd2e1c86a80}}
        fd = <optimized out>
        list = <optimized out>
        nlist = <optimized out>
        cp = <optimized out>
#9  0x00007fd2e4cd047c in malloc_printerr (str=str@entry=0x7fd2e4df41e0 "munmap_chunk(): invalid pointer") at malloc.c:5347
No locals.
#10 0x00007fd2e4cd06cc in munmap_chunk (p=<optimized out>) at malloc.c:2830
        pagesize = <optimized out>
        size = <optimized out>
        __PRETTY_FUNCTION__ = "munmap_chunk"
        mem = <optimized out>
        block = <optimized out>
        total_size = <optimized out>
#11 0x0000000041ac9633 in ?? ()
No symbol table info available.
#12 0x000055b2cce27950 in ?? ()
No symbol table info available.
#13 0x00007fd2e1c86ca0 in ?? ()
No symbol table info available.
#14 0x000055b2cc4bdde0 in ?? ()
No symbol table info available.
#15 0x0000000000000000 in ?? ()
No symbol table info available.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fd2e4c5d859 in __GI_abort () at abort.c:79
#2  0x000055b2ca4c66ca in ?? ()
#3  0x000055b2ca5041bd in ?? ()
#4  0x000055b2ca556467 in ?? ()
#5  <signal handler called>
#6  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#7  0x00007fd2e4c5d859 in __GI_abort () at abort.c:79
#8  0x00007fd2e4cc83ee in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7fd2e4df2285 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#9  0x00007fd2e4cd047c in malloc_printerr (str=str@entry=0x7fd2e4df41e0 "munmap_chunk(): invalid pointer") at malloc.c:5347
#10 0x00007fd2e4cd06cc in munmap_chunk (p=<optimized out>) at malloc.c:2830
#11 0x0000000041ac9633 in ?? ()
#12 0x000055b2cce27950 in ?? ()
#13 0x00007fd2e1c86ca0 in ?? ()
#14 0x000055b2cc4bdde0 in ?? ()
#15 0x0000000000000000 in ?? ()

**Comment by JosephMcc** [comment]
Pinta isn't part of the default install. It comes out of the Ubuntu repos and isn't under our control. We've reviewed it as a default app and one of the reasons we didn't go with it was the instability. Problems with it need to be reported to the Pinta devs directly https://github.com/PintaProject/Pinta
