### ISSUE TITLE
Celluloid constant crashing.

### ISSUE THREAD

**Issue by crhy** [linuxmint/mint20.1-beta#55]
In the new beta Celluloid is crashing non-stop.  No system error report in the system reports app.

**Comment by xenopeek** [comment]
This observation needs more information and troubleshooting to be able to work on it. See the reporting bugs section in the toubleshooting guide: https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/why.html

Things to include:

1. System Information from the System Report program
2. Start Celluloid from the terminal and copy any output after it crashes
3. Is there anything common between the crashes; file format you're playing for example

**Comment by crhy** [comment]
Not sure why this is closed. This is definitely still an issue:  https://www.youtube.com/watch?v=_DEzgGNIqZg

**Comment by crhy** [comment]
Ran from the console:  No errors presented.  The file did finally open, but it took FOREVER, then the audio played, the screen was black, once I began seeking, the picture showed up.  Definitely broken still.  Yes, I ran all the updates.

**Comment by crhy** [comment]
[code]
System:    Kernel: 5.4.0-58-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: MATE 1.24.0 
           wm: marco dm: LightDM Distro: Linux Mint 20.1 Ulyssa base: Ubuntu 20.04 focal 
Machine:   Type: Desktop System: Dell product: OptiPlex 3040 v: N/A serial: <filter> Chassis: 
           type: 3 serial: <filter> 
           Mobo: Dell model: 05XGC8 v: A01 serial: <filter> UEFI [Legacy]: Dell v: 1.11.3 
           date: 07/19/2019 
CPU:       Topology: Quad Core model: Intel Core i5-6500 bits: 64 type: MCP arch: Skylake-S rev: 3 
           L2 cache: 6144 KiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 25599 
           Speed: 2693 MHz min/max: 800/3600 MHz Core speeds (MHz): 1: 2663 2: 2680 3: 2696 
           4: 2700 
Graphics:  Device-1: AMD Cedar [Radeon HD 5000/6000/7350/8350 Series] driver: radeon v: kernel 
           bus ID: 01:00.0 chip ID: 1002:68f9 
           Display: x11 server: X.Org 1.20.8 driver: ati,radeon unloaded: fbdev,modesetting,vesa 
           compositor: marco resolution: 1920x1080~60Hz, 1440x900~60Hz 
           OpenGL: renderer: AMD CEDAR (DRM 2.50.0 / 5.4.0-58-generic LLVM 10.0.0) 
           v: 3.3 Mesa 20.0.8 compat-v: 3.1 direct render: Yes 
Audio:     Device-1: Intel 100 Series/C230 Series Family HD Audio vendor: Dell 
           driver: snd_hda_intel v: kernel bus ID: 00:1f.3 chip ID: 8086:a170 
           Device-2: AMD Cedar HDMI Audio [Radeon HD 5400/6300/7300 Series] driver: snd_hda_intel 
           v: kernel bus ID: 01:00.1 chip ID: 1002:aa68 
           Device-3: Logitech HD Pro Webcam C920 type: USB driver: snd-usb-audio,uvcvideo 
           bus ID: 1-5:3 chip ID: 046d:082d 
           Device-4: C-Media USB Advanced Audio Device type: USB 
           driver: hid-generic,snd-usb-audio,usbhid bus ID: 1-4:2 chip ID: 0d8c:016c 
           Sound Server: ALSA v: k5.4.0-58-generic 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Dell 
           driver: r8169 v: kernel port: d000 bus ID: 02:00.0 chip ID: 10ec:8168 
           IF: enp2s0 state: up speed: 1000 Mbps duplex: full mac: <filter> 
Drives:    Local Storage: total: 931.51 GiB used: 12.33 GiB (1.3%) 
           ID-1: /dev/sda vendor: Samsung model: SSD 860 EVO 1TB size: 931.51 GiB speed: 6.0 Gb/s 
           serial: <filter> 
Partition: ID-1: / size: 95.62 GiB used: 12.22 GiB (12.8%) fs: ext4 dev: /dev/sda1 
           ID-2: /boot size: 487.9 MiB used: 105.6 MiB (21.6%) fs: ext4 dev: /dev/sda5 
USB:       Hub: 1-0:1 info: Full speed (or root) Hub ports: 10 rev: 2.0 chip ID: 1d6b:0002 
           Device-1: 1-4:2 info: C-Media USB Advanced Audio Device type: Audio,HID 
           driver: hid-generic,snd-usb-audio,usbhid rev: 1.1 chip ID: 0d8c:016c 
           Device-2: 1-5:3 info: Logitech HD Pro Webcam C920 type: Video,Audio 
           driver: snd-usb-audio,uvcvideo rev: 2.0 chip ID: 046d:082d 
           Device-3: 1-6:4 info: Dell Dell MS116 USB Optical Mouse type: Mouse 
           driver: hid-generic,usbhid rev: 2.0 chip ID: 413c:301a 
           Device-4: 1-8:5 info: Dell Dell KB216 Wired Keyboard type: Keyboard,HID 
           driver: hid-generic,usbhid rev: 1.1 chip ID: 413c:2113 
           Hub: 2-0:1 info: Full speed (or root) Hub ports: 4 rev: 3.0 chip ID: 1d6b:0003 
Sensors:   System Temperatures: cpu: 51.0 C mobo: 29.8 C gpu: radeon temp: 61 C 
           Fan Speeds (RPM): N/A 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/obsproject-obs-studio-focal.list 
           1: deb http: //ppa.launchpad.net/obsproject/obs-studio/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //packages.linuxmint.com ulyssa main upstream import backport
           2: deb http: //archive.ubuntu.com/ubuntu focal main restricted universe multiverse
           3: deb http: //archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse
           4: deb http: //archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ focal partner
Info:      Processes: 236 Uptime: 59m Memory: 7.72 GiB used: 2.46 GiB (31.9%) Init: systemd v: 245 
           runlevel: 5 Compilers: gcc: 9.3.0 alt: 9 Client: Unknown python3.8 client inxi: 3.0.38 
[/code]
