### ISSUE TITLE
Hypnotix constantly crashing.

### ISSUE THREAD

**Issue by crhy** [linuxmint/mint20.1-beta#56]
I tried getting it to work several different ways, it only opened once briefly, and then crashed again.  This is whether or not any other app was open, but it seemed to crash faster with OBS open.

https://www.youtube.com/watch?v=Lb6rofiwYvs

Here I summarize several bugs I encountered on real hardware after a basic install of Mint 20.1 MATE version.

**Comment by xenopeek** [comment]
This observation needs more information and troubleshooting to be able to work on it. See the reporting bugs section in the toubleshooting guide: https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/why.html

Things to include:

1. System Information from the System Report program
2. Start Hypnotix from the terminal and copy any output after it crashes
3. Is there anything else common between when it crashes? Like what are you doing in Hypnotix or does it also crash when you just have it open and are doing things in another program? Context and details help.

**Comment by clefebvre** [comment]
Closing as it's only an observation. Quick suggestion though in case you're using a VM, I've seen really weird things happen in VMs when WIDs are used, and Hypnotix does use this... switch your renderer to VMSVGA with 3D enabled.

I'm planning to watch the video and take notes. It looks like it highlights many paper cuts. It's a long video though :)

**Comment by crhy** [comment]
This is not a VM.  This was on bare metal.  I've uploaded the system information and several screen shots on related closed (not fixed) bugs.  I've ordered a new gfx card, will report back when it gets here on the 8th.
