### ISSUE TITLE
Weird Sound Preferences / Volume Menu too short, can't click.

### ISSUE THREAD

**Issue by crhy** [linuxmint/mint20.1-beta#57]
I show an example of this during the video:

https://www.youtube.com/watch?v=Lb6rofiwYvs

**Comment by JosephMcc** [comment]
I sat through the first hour of that video. It's very possible the temporary glitch is caused from switching and changing compositors. Those sorts of things happen sometimes when doing that.

**Comment by clefebvre** [comment]
I can't browse through the video. If we're talking about a GTK popupmenu then it's a know bug and also a wontfix upstream from GNOME. They started using popovers and they're not really interested in fixing that. One way to prevent this from happening is to have the content not change once the menu is open.. that's a design restriction on the developers. It should be addressed upstream to MATE directly.

**Comment by crhy** [comment]
Which leads again to how we notify the MATE devs....

**Comment by clefebvre** [comment]
I think it's going to be a won't fix in MATE because of the won't fix in GNOME, but you can try.

https://github.com/mate-desktop/mate-applets/issues
