### ISSUE TITLE
Backgrounds Settings takes too long to load all the backgrounds.

### ISSUE THREAD

**Issue by crhy** [linuxmint/mint20.1-beta#59]
This has been an issue in most of the last releases, not new to 20.1.

Maybe we need smaller thumbnails?

https://www.youtube.com/watch?v=Lb6rofiwYvs

**Comment by clefebvre** [comment]
No, this is for MATE to fix. They need to support categories so as to not load all at once, and do it in a thread so it doesn't lag the way it does.

**Comment by crhy** [comment]
Hmmm Can we link the MATE github from here?

**Comment by clefebvre** [comment]
Yes.
