### ISSUE TITLE
Desktop Settings : Compiz missing.

### ISSUE THREAD

**Issue by crhy** [linuxmint/mint20.1-beta#60]
I talk about this at length in the video, and we've also discussed it in detail on the blog post, etc..

https://www.youtube.com/watch?v=Lb6rofiwYvs

**Comment by xenopeek** [comment]
Already answered on the blog: https://blog.linuxmint.com/?p=3990#comment-171922

**Comment by xenopeek** [comment]
Update from the monthly news: https://blog.linuxmint.com/?p=4005

> Finally, a quick note to Compiz fans. Compiz will be back, and functional out of the box, in the stable release of the MATE and Xfce editions. Thank you for your feedback.

**Comment by crhy** [comment]
YAY!  Will I have to reinstall Mint Beta from scratch, or will it just show up in future updates?  Still not there as of now.

**Comment by clefebvre** [comment]
You'll need to install it yourself, it won't be brought back by a dependency.

**Comment by crhy** [comment]
Hey guys, lots of weirdness in the Compiz Config after installing and updating.

It did show up in the desktop Windows Settings, and:

Installed Compiz, default config working, however some issues, no 3d desktop cube plugin, maybe I'm missing a package.... BRB.....  Just added compiz-plugins from synaptic....  Now I have Desktop Cube.

Enhanced Zoom was working great out of the box!

Changing settings in desktop cube and Rotate Cube do not actually change any settings.  Maybe a Configuration permissions issue?  Going to run all the latest updates that just showed up in the Update Manager, Reboot, and report back....

But hey!  Now I have this bug report site as a web app.  Pretty cool!  Would be cool to actually have that setup by default for all users.  Think of the feedback and quality control you guys would be getting then!

Anyway, Compiz is working great, other than the config for desktop cube and rotate cube.  Fingers crossed the reboot solves it....
