### ISSUE TITLE
Install and Uninstall not working in the Start Menu.  No Search result for Install apps.

### ISSUE THREAD

**Issue by crhy** [linuxmint/mint20.1-beta#61]
I also documented that here:
https://www.youtube.com/watch?v=Lb6rofiwYvs

**Comment by JosephMcc** [comment]
Install/Uninstall seems to be fine from the applications list just not from the favorites.

**Comment by xenopeek** [comment]
Assuming this is about 20.1-beta MATE. Indeed favorites in mintMenu does not support install/uninstall. You could make a feature request for that here: https://github.com/linuxmint/mintmenu/issues

That there are no search results for installable programs looks to be a bug. Same is reproducible on Mint 20 so it's not a 20.1-beta bug.

**Comment by xenopeek** [comment]
That search for packages to install doesn't work is fixed here: https://github.com/linuxmint/mintmenu/pull/261

**Comment by crhy** [comment]
It used to work.  How long has this feature been missing?  https://www.youtube.com/watch?v=_DEzgGNIqZg

**Comment by crhy** [comment]
Just confirmed, it's from the start menu at any selection, not just favorites.  Why are you guys closing bugs that are still open?
