### ISSUE TITLE
GIMP not installed by default.

### ISSUE THREAD

**Issue by crhy** [linuxmint/mint20.1-beta#62]
This decisions seems insane to me.  I'm not sure who advocated for removing GIMP or why, but it's a dumb idea.  We should have GIMP out of the box.

**Comment by JosephMcc** [comment]
Despite your personal preference a lot of users find Gimp overly complicated and confusing when they just want to do simple things. GIMP has already been removed from the default selection for a release or two with very little negative feedback. People who need what GIMP can do, already know about it and can install it themselves.

**Comment by crhy** [comment]
Terrible Decision.  This car comes with a stereo!  Not everybody wants a stereo.  Stereo removed.
