### ISSUE TITLE
Video not showing up in VLC when playing a video.

### ISSUE THREAD

**Issue by crhy** [linuxmint/mint20.1-beta#67]
Right around the 37 min mark of this video you can see the issue:

https://www.youtube.com/watch?v=Lb6rofiwYvs

**Comment by JosephMcc** [comment]
In the video you seem to have problems with both VLC and Celluloid. Both work fine here so wonder if something is going on for you when it comes to video playback in general.

**Comment by clefebvre** [comment]
Ah.. there's probably a moment in the video where we see the display drivers and all... it's too long to find though :+1: 

This kind of video is gold for me especially for papercuts but I really need time to go through it and it's not something I can do in the middle of a BETA rush when we're trying to squash release blockers.

I'm putting it aside.

For a report like this normally you'd need to investigate the 3D renderer with something like `inxi -Gxx`, we'd then have a problem with either the drivers, the driver manager possibly, or VLC itself (unlikely). Considering the amount of crashes though I've a feeling this is a VM..

**Comment by crhy** [comment]
rhy@rhy-OptiPlex-3040:~$ inxi -Gxx
Graphics:
  Device-1: AMD Cedar [Radeon HD 5000/6000/7350/8350 Series] driver: radeon 
  v: kernel bus ID: 01:00.0 chip ID: 1002:68f9 
  Display: x11 server: X.Org 1.20.8 driver: ati,radeon 
  unloaded: fbdev,modesetting,vesa compositor: marco 
  resolution: 1920x1080~60Hz, 1440x900~60Hz 
  OpenGL: renderer: AMD CEDAR (DRM 2.50.0 / 5.4.0-58-generic LLVM 10.0.0) 
  v: 3.3 Mesa 20.0.8 compat-v: 3.1 direct render: Yes 
rhy@rhy-OptiPlex-3040:~$ 

Still definitely an issue.  Just ran all the updates.  This is in Celluloid, VLC, and hypnotix.  Why are we closing bugs that have not been fixed?  How does that help anyone?

**Comment by crhy** [comment]
![Screenshot at 2020-12-31 17-09-39](https://user-images.githubusercontent.com/21183395/103432868-ff8e0680-4b8a-11eb-8835-c9ad7a91ec39.png)

**Comment by clefebvre** [comment]
This looks like a driver issue to me. @crhy I'd suggest to try a 5.8 kernel to see if it helps.

**Comment by crhy** [comment]
What's the best way to try out the 5.8 kernel?  Will try ASAP.

**Comment by clefebvre** [comment]
Using the Update Manager -> View -> Linux Kernels

**Comment by crhy** [comment]
Will try tonight.  Just FYI Got the updated hypnotix, and it was working a bit better.  Could get to live TV even with OBS open.  So that was cool.  Saw a local middle school choir on a local station.  Never would have seen that in my life, so hypnotix is kind of cool.  Might give a new lease on life to local small TV stations....  If it catches on.

**Comment by crhy** [comment]
Yeah, Upgraded to the 5.8 kernel, Still weird issues in video playback.  No Driver is showing up in Driver Manager, and I do have an after market graphics card.

So.... Yeah, not sure what to do about that.

**Comment by crhy** [comment]
So what happens is (in VLC, Celluloid, AND hypnotix):  The app opens, there's a weird freeze, both monitors go black, and then finally the desktop comes back, the app starts playing the video but shows now video.  The audio starts working right away, but I have to do a manual seek for the video to start showing up.  Just ran all the updates, will report back in a few minutes after a reboot.

Hypnotix is cool though!  Surprisingly good audio and video quality, lots of cool content.  Very cool app.  Great job guys!

**Comment by crhy** [comment]
![20210103_125148](https://user-images.githubusercontent.com/21183395/103490932-5f6ef200-4dc3-11eb-8748-ba3f79968f44.jpg)

**Comment by crhy** [comment]
Updated Beta Test Video:  https://youtu.be/yS53regC4qw
