### ISSUE TITLE
root console not changing color of user to red when in root.

### ISSUE THREAD

**Issue by crhy** [linuxmint/mint20.1-beta#68]
all white does not make it clear that you are in root.

sudo su
Password:

User all white, no red.

**Comment by clefebvre** [comment]
Agreed but not a release blocker. I'll add an item so we can look at it for 20.2.

**Comment by crhy** [comment]
This is probably upstream, no?  Do we have a way to tag upstream directly from these reports?

**Comment by clefebvre** [comment]
It is upstream. When it was red in Mint (in the past) it was already colorless in Ubuntu. What happened is that we aligned with upstream to get closer to them and deviate less on this. I do like it red better myself, but sometimes it's good to not differ when it's not really needed.

I can't remember if it was "ever" red in Ubuntu though... it might be a design choice on their side.
