### ISSUE TITLE
Clock defaulting to 24 hour format in panel.

### ISSUE THREAD

**Issue by crhy** [linuxmint/mint20.1-beta#69]
Very odd choice.  Almost everyone I know uses 12 hr pm/am nomenclature.

**Comment by xenopeek** [comment]
Not a beta bug; different personal preference. Please read the why, when, what, where and how chapters of our troubleshooting guide to make good bug reports: https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/why.html

**Comment by crhy** [comment]
I read the article.  But why are we defaulting to the less popular option?
