### ISSUE TITLE
Nemo: Icon for nemo.desktop was changed from 'folder' to 'system-file-manager'

### ISSUE THREAD

**Issue by Acheron17** [linuxmint/mint20.1-beta#7]
Icon for nemo.desktop was changed from 'folder' to 'system-file-manager'.  This has the effect of an unattractive icon for Mint-X.  This also affects other popular icon schemes used in Cinnamon for Mint-X.  This is because they do not have a link from 'system-file-manager' to 'folder'.

Fixed the issue by copying /usr/share/applications/nemo.desktop to ~/.local/share/applications and editing Icon=folder.

**Comment by ChooChooAl** [comment]
I saw this too but I kinda like the system-file-manager icon being used.  I have custom theme and obviously it would be simple to link the icons to return the 'folder' icon but I like the differentiation between system file manager in panel and and the folder icons in nemo.  But this is my personal opinion.

**Comment by clefebvre** [comment]
Can you provide a screenshot to show the issue?

**Comment by Acheron17** [comment]
Here is Mint-Y default icon scheme and Mint-X default icon scheme.
![Screenshot-from-2020-12-16-17-49-57](https://user-images.githubusercontent.com/45599505/102416329-9f626680-3fc7-11eb-9153-8b0c22ec310d.png)
![Screenshot-from-2020-12-16-17-49-15](https://user-images.githubusercontent.com/45599505/102416347-a7220b00-3fc7-11eb-8cde-4a964026fd83.png)

**Comment by clefebvre** [comment]
Thanks.

**Comment by ChooChooAl** [comment]
Actually I'd go a step further.  The system-file-manager could be the file cabinet as technically that is the top the of food chain.   Much like in an office, you open the file cabinet to get folders.
But once the folders are open, they are folders.   Here is how I see the panel and nemo.   This was captured on Mint 20 and I modified the panel launcher icon to be the system-file-manager.png icon to show my example.  Normally (in Mint 20 and earlier) all the icons are the file folder for the current icon them.   System-file-manager.png was never used until mint 20.1.   I don't think users would like little file cabinets strung across the panel.
This was captured on Mint 20 and I modified the panel launcher icon .
![Panel](https://user-images.githubusercontent.com/26556059/102479295-b8513300-402c-11eb-9bee-fcdbf1801020.png)
This is how Nemo display folders 
![nemo](https://user-images.githubusercontent.com/26556059/102479367-ce5ef380-402c-11eb-9ebd-4a6aba87988a.png)
And this is what 20.1 is showing in the panel.  Kinda confusing to me.
![Mint 20 1](https://user-images.githubusercontent.com/26556059/102479525-ffd7bf00-402c-11eb-840a-540d0e5d11e2.png)
The above image really should have the same icon for system-file-manager in the launcher area, I just forgot that I had modified it with my personal icon.

**Comment by clefebvre** [comment]
It was fixed here: https://github.com/linuxmint/nemo/issues/1686.

The reason I say "fixed" is because technically Nemo should let themes distinguish between the app and the places.

That said, in terms of outcome, I agree with you, it doesn't look right. Users don't think of "home" shortcuts as a file manager, certainly not of opened places as file managers either... in fact it's arguable whether they ever think of a file manager in opposition to just an FS or places and folders.

So I'll change this in Mint-X, that way it will still look right but nemo will let icon themes decide appropriately.

**Comment by clefebvre** [comment]
Fixed in mint-x-icons 1.5.6.
