### ISSUE TITLE
Default to Dark theme for the start menu to match the task bar out of the box.

### ISSUE THREAD

**Issue by crhy** [linuxmint/mint20.1-beta#73]
See here:  https://www.youtube.com/watch?v=Lb6rofiwYvs

**Comment by janos-r** [comment]
Just your opinion man... and also not a very good one for your average user that mint is targeting.
If you want a light taskbar, there is mint-X. Or any kind of custom themes for the start-menu color.
If you make some custom theme incredibly popular, it could even become the default in some future. Not a bug-fix though.

**Comment by crhy** [comment]
The start menu doesn't match the panel.  The default looks dumb.  Why not just make the start menu and the panel match out of the box?  This is a design bug.  Why is it closed?

**Comment by xenopeek** [comment]
It's closed because this isn't a release blocker.
