### ISSUE TITLE
Libre Office will not Expand back out of the Task Bar while Welcome Screen is Open.

### ISSUE THREAD

**Issue by crhy** [linuxmint/mint20.1-beta#74]

**Comment by JosephMcc** [comment]
It would help if you provide basic info like the DE you are using. Can't reproduce in Cinnamon.

**Comment by xenopeek** [comment]
Not reproducible on 20.1-beta Cinnamon, MATE or Xfce. Please read the why, when, what, where and how chapters of our troubleshooting guide to make good bug reports: https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/why.html
