### ISSUE TITLE
Blinking caret leaves dot when at first character of line in some programs

### ISSUE THREAD

**Issue by dancesWithBugs** [linuxmint/mint20.1-beta#77]
Here's a video of a pidgin chat. Notice how the caret leaves a dot behind when it disappears. This only happens at the beginnings of lines and only in some programs. So far I've encountered this in pidgin and xed.

![blinking_caret](https://user-images.githubusercontent.com/75453205/103229060-97dd7e80-4932-11eb-858a-05b332f673c6.gif)

You should be able to reproduce this by booting into the 20.1 beta Cinnamon live system and opening xed. No further changes were necessary on my system.

**Comment by xenopeek** [comment]
Cinnamon, MATE or Xfce? Default themes or have you set custom system themes? Default fonts & font sizes or have you set system custom fonts? Can you reproduce while booted from the 20.1-beta ISO?

**Comment by dancesWithBugs** [comment]
Fair enough. It's Cinnamon and reproducible on the live system with default settings in xed (you can also `apt-get install pidgin` to compare). I've edited my original post to include that information.

**Comment by xenopeek** [comment]
Strange. Reproducible on 20.1-beta MATE and Xfce as well, and also on Linux Mint 20.

Also in others Gtk programs like Gedit and Mousepad but not in Qt programs like Kate. That might suspect upstream Gtk issue but it's **not reproducible on Ubuntu 20.04**, or LMDE 4, so this looks to be an issue introduced in Linux Mint.

**Comment by xenopeek** [comment]
Same happens in Gedit on Ubuntu 20.04 when monospace font size is set smaller than 13. The default monospace font size on 20.1-beta Cinnamon is 10; increasing it to 13 makes the issue go away. So like your other issue about jumping lines with font size set < 12, this is an upstream issue in GtkTextView widget.
