### ISSUE TITLE
Calendar: Close button in About dialog does not work

### ISSUE THREAD

**Issue by laurenrad** [linuxmint/mint20.1-beta#81]
The close button in 'About Calendar' does not close the window, as it would in other applications (such as Calculator).
The upstream version does not have a close button, so I presume it's been patched downstream to have one.
Steps to reproduce:
1. Open Calendar
2. Open the Calendar's application menu.
3. Click 'About Calendar'
4. Click the close button.
This bug also seems to exist on 20.0, but happens on a fresh install of the 20.1 Beta downloaded yesterday and updated today.
No relevant errors are echoed to stderr and there do not seem to be any log errors for Calendar other than "Cinnamon warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x6e00007 (Calendar)".

**Comment by ghost** [comment]
I can't see any problems with calendar,all close buttons working how they should work.

**Comment by janos-r** [comment]
I reproduced this in 19.3. It's probably an old calendar issue and should be in the github of that app and not this beta probably.

**Comment by laurenrad** [comment]
I'll double check this if it's not closed first, but I forgot to include a couple bits of clarifying info:
- This is present for me in 3.36.1
- I am referring to the close button in the dialog, not the window manager button, which does work.

**Comment by janos-r** [comment]
Yes, the version on 19.3 is calendar 3.28.2 and it has the same behavior. This is really not a beta release issue.
If I'm not mistaken the upstream is https://wiki.gnome.org/Apps/Calendar and the contributions there are on gitLab.
I even found the issue discussed here:
https://gitlab.gnome.org/GNOME/gnome-calendar/-/issues/511
It is still open there. No idea why such a small thing is taking them months to address.
But as I said, not a mint beta release thing. Somebody will close this.

**Comment by laurenrad** [comment]
Got it, I assumed since the Ubuntu upstream version didn't use the button, it was a Mint thing, but it looks like that isn't the case. I'll look at it upstream.
