### ISSUE TITLE
mintmenu: Favorites section should have a scrolledwindow

### ISSUE THREAD

**Issue by crhy** [linuxmint/mint20.1-beta#82]
![Screenshot at 2020-12-31 17-13-50](https://user-images.githubusercontent.com/21183395/103432897-935fd280-4b8b-11eb-81cb-74c6450d53ab.png)

Add Favorites.  Add more than can be displayed in the default display.  No new favorite.  Deleting an above favorite, then you can see the new favorite you added again, so it's just a display issue.

**Comment by clefebvre** [comment]
In mintmenu? You mean the favorite section is missing a scrolledwindow?

**Comment by crhy** [comment]
Yes Exactly.  If you add a bunch of favorites, the newest ones just disappear unless you go edit the menu and add rows or columns, or shrink the icon/label size.

**Comment by rdrolis** [comment]
If I understand the issue the OP is bringing up correctly, I cannot reproduce. This already works in Cinnamon. See attached screen grab.

https://user-images.githubusercontent.com/49482101/103439817-de1e3080-4c05-11eb-8ae9-bc9bc57c7aaf.mp4

**Comment by crhy** [comment]
rdrolis:  This is MATE

**Comment by janos-r** [comment]
How is the above scrnshot related? Did this suddenly break in 20.1 or is it rather an enhancement idea?
https://community.linuxmint.com/idea/welcome

**Comment by clefebvre** [comment]
It's not related.

**Comment by crhy** [comment]
Yeah, sorry about the screenshot.  Every time I hit capture it just disappeared.  My bad.

**Comment by xenopeek** [comment]
@crhy for future reference: to take a screenshot of menus open the screenshot program, set it up to take a screenshot after X seconds delay, then open the menu you want to screenshot and wait till the screenshot program takes the screenshot.

**Comment by crhy** [comment]
@xenopeek Good Call.  Will do that next time.  Thanks!
