### ISSUE TITLE
Gradient color is banding

### ISSUE THREAD

**Issue by onyx82** [linuxmint/mint20.1-beta#83]
Gradient color is banding in image or video
All versions a kernel there is Gradient color is banding
ASRock model: J4105M ,Intel UHD Graphics 600
my post for ubuntu 20.04      https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1909126

**Comment by clefebvre** [comment]
I'll close this one here since it won't hold the release and it's upstream. @onyx82 if you can, put a screenshot in Launchpad to illustrate the problem.
