### ISSUE TITLE
xapp-status-icon: nm-applet can't start with Turkish locale

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/mint20.1-beta#84]
Hi,

First of all, thank you very much for your efforts regarding the new releases.

Nm-applet can't start properly on login with Turkish language. But if I switches to English locale, it working properly. The issue may be in other local languages. 

I think, this issue related with that commit. https://github.com/linuxmint/xfce4-xapp-status-plugin/commit/2416f6099816a2494cf13aa5f75ef456540344ee

If I run nm-applet with following command, it  working with Xfce's notification area instead of xapp status plugin.

`dbus-launch nm-applet`

I get the following xsession error related this issue.

`(nm-applet:4539): GLib-GIO-CRITICAL **: 00:27:51.645: g_bus_own_name_on_connection: assertion 'g_dbus_is_name (name) && !g_dbus_is_unique_name (name)' failed`

-------------------------

Addition: If I install network-manager-gnome package from focal with following command, nm-applet working on login with notification area.

`sudo apt install network-manager-gnome/focal`

**Comment by clefebvre** [comment]
Thanks @kelebek333

**Comment by clefebvre** [comment]
Fixed in libxapp.

**Comment by kelebek333** [comment]
Thanks @clefebvre and @mtwebster  ,

Issue solved by this fix.
