### ISSUE TITLE
Cinnamon: Failed to load module "xapp-gtk3-module"

### ISSUE THREAD

**Issue by demetera** [linuxmint/mint20.1-beta#87]
It's seems there's an issue with xapp xfce module.
When running applications (so far I've noticed problem with spotify, qjackctl, the same with LMMS AppImage from their official website) from terminal, error message appears : 
`Gtk-Message: <timestamp>: Failed to load module "xapp-gtk3-module"`

Meanwhile applications themselves are running well.
Reproduced on 2 PCs.

Kernel 5.4.86 (compiled by myself with native config. just added midi device support to sound/usb/quirks-table.h)
From 3rd party applications I've installed only Google Chrome from official deb-package.

`echo $GTK_MODULES`
showing this
`xapp-gtk3-module:gail:atk-bridge`

**Comment by clefebvre** [comment]
This is fixed by https://github.com/linuxmint/xapp/commit/e846e76a392d44d211b7007691358f173f1b44a3. It will come as an update.
