### ISSUE TITLE
MATE | Keyboard sequence to kill the X server option

### ISSUE THREAD

**Issue by martywd** [linuxmint/mint20.1-beta#89]
Distributor ID:	Linuxmint
Description:	Linux Mint 20.1
Release:	20.1
Codename:	ulyssa
MATE

Bare metal install, system is up-to-date as I type.  Notice that 'Ctrl+Alt+Backspace' keyboard shortcut wasn't killing X.

In the past in (LM MATE) Control Center | Hardware | Keyboard | Layouts |  Options...' , the '**Keyboard sequence to kill the X server option**' option was ticked by default.  I notice today, that at present in this MATE beta this is no longer the case.

Is this an over-sight or is it now intended that the user enables this option if wanted on their own?
.

**Comment by crhy** [comment]
I noticed this too but forgot to report.  Thank you for reporting!

**Comment by xenopeek** [comment]
Perhaps longer ago but on Linux Mint 19.3 and 20, and on Ubuntu MATE 20.04, the key sequence to kill the X server isn't set either so I assume this is a MATE default. As this isn't an issue blocking the release of 20.1 I'm closing this here.
