### ISSUE TITLE
Hypnotix - Can't close window

### ISSUE THREAD

**Issue by MenthaSuaveolens** [linuxmint/mint20.1-beta#9]
Hypnotix om LM 20.1

1. Open a TV-station => new window pops up
2. Try to close the newly opened window (Cross Top Right) => Playing video stops but window remains open
3. Press right-mouse-button on the taskbar -> close => nothing happens
4. Close Hynotix (Cross Top Right) => all windows get closed

**Comment by clefebvre** [comment]
Hi @MenthaSuaveolens 

In what desktop is that?

I don't understand how you get a new window in point 1.... can you show us a screenshot or a video of it?

**Comment by MenthaSuaveolens** [comment]
Well, fresh install of LM 20.1 in a virtual machine. As soon as one selects a station, a python-window is opened
![HynotixDoubleWindow](https://user-images.githubusercontent.com/47174957/102507450-8e2b5f80-4084-11eb-9867-cb4764eae40d.png)

**Comment by kneekoo** [comment]
Same issue here in QEMU, with **-vga virtio** _(driver virtio-pci)_ and **-vga std** _(driver bochs-drm)_ on Intel HD Graphics 4600 (HSW GT2):

I tried to close that window and it stuck like that, then I cliked on a different station and it played inside the window, while the external one didn't change. The separate window closes normally when you exit Hypnotix, though.

DEs: Cinnamon, MATE, Xfce (all 3 tested with both qemu drivers)
![HynotixDoubleWindow](https://i.imgur.com/G8004Ta.jpg)

**Comment by clefebvre** [comment]
@MenthaSuaveolens you're in QEMU as well?

**Comment by MenthaSuaveolens** [comment]
No, I'm not. Running LM Cinnamon 20.1 in a virtual machine (VirtualBox) on a LM Cinnamon 20.0-host.

**Comment by clefebvre** [comment]
did you change the MPV options?

**Comment by MenthaSuaveolens** [comment]
When booting up with a live-usb-stick on my machine, Hypnotix plays well (As it does on LM 20.0 on this machine). Then I started the VM booting up from the .iso-file. I get the double window. In the latter case, I just started Hypnotix without changing anything. It looks that virtualisation is the culprit.

**Comment by clefebvre** [comment]
OK, I can reproduce it with VBoxSVGA and 3D disabled.

**Comment by clefebvre** [comment]
I'm sorry I can't fix this on my side, this is using mpv's built-in WID mechanism which I expect is basically X11's embed/plug mechanism. If Vbox can't handle that, that's on Virtualbox to fix.

On our side I'd like to experiment with multiple backends (VLC etc..) but we're not there yet at all. I'll close this for this BETA in the meantime.

**Comment by clefebvre** [comment]
For a workaround, run Virtualbox with 3D ON, and VMSVGA.
