### ISSUE TITLE
Blueproximity

### ISSUE THREAD

**Issue by tiktaalik-dev** [linuxmint/mint20.1-beta#91]
Hello there,

This is not really a bug report, but I couldn't find a more suitable place for this.
Since last year Blueproximity hasn't been available in Linux Mint repositories, and most other distributions, because Python 2.7 reached End of Life and the original Blueproximity application only supported that version of Python.
As the original code was licensed under the GPL v2 (and as I couldn't get an answer from the original author), I forked the project and updated Blueproximity to make it compatible with Python 3. It's now fully functional and stable so I'm wondering if you guys may add it back into the repositories for the next version of Linux Mint?
Please find the project code on [https://github.com/tiktaalik-dev/blueproximity](https://github.com/tiktaalik-dev/blueproximity)

Thanks for your great work!
Cheers,
Rodrigo Gambra

**Comment by xenopeek** [comment]
Kudos to you for reviving an old project you need! The Linux Mint repository is limited mostly to software developed and/or maintained by Linux Mint. In addition it uses a package base repository from which programs like Blueproximity would be installed. For example for Linux Mint 20.x that is Ubuntu 20.04, which in turn imports most packages from Debian. To reach the widest group of users if you could get the package into the Debian repository ... it would get to Ubuntu from there and then it would also be available on future Linux Mint.

Alternatively you could maybe build a .deb package so users can download that from GitHub to install it, or an AppImage so users on any Linux distro can download & run it, or a flatpak on Flathub.org so users on any Linux distro can install it from there, or you could set up a PPA (personal package archiver) on Launchpad.net to build .deb packages and Ubuntu and Linux Mint users can then add the PPA to their system for installing & updating it.
